<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Show All MP3 Players_fas fa-home</name>
   <tag></tag>
   <elementGuidId>c210b4ad-dca5-4b8f-91a4-2f78e4c5f8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-cart']/ul/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c3371800-8c81-4da5-b9f8-6d47ba642ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-home</value>
      <webElementGuid>517efd9c-9747-4c6d-b7be-06a00dddab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-cart&quot;)/ul[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[1]/i[@class=&quot;fas fa-home&quot;]</value>
      <webElementGuid>4d1be8f1-532d-4fd5-90e1-cfcd2e5d2eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-cart']/ul/li/a/i</value>
      <webElementGuid>744d3ac6-71be-499a-9e66-2edd13991c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/ul/li/a/i</value>
      <webElementGuid>7079fb8e-3204-431b-81d9-5109458583b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
