<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>TestSuite02</description>
   <name>TestSuite02</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ff33b715-a67b-4a0f-81b9-bb9cc833d5a0</testSuiteGuid>
   <testCaseLink>
      <guid>cf1be05f-c829-49c1-a1db-bae7d468fa76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAssist/GenerateCodeUseCase01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21fd0316-f072-4614-b96b-cb1cf5a96c2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>affdcb2b-2f6a-4a25-a608-51594ee33fea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29743426-a077-44a3-9910-f5bd251c6bd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAssist/GenerateCodeUseCase02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4cf0fc2-960d-4ea8-8436-6b401bf5d726</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15203d8-bfbb-4cdb-852e-26c86ea1dd4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5682b35f-9ba9-4c49-add8-f21b7d9d9f87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StudioAssist/GenerateCodeUseCase03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e51a69d-80c6-4249-a65e-6461a6d56aab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
