<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name must be between 3 and 32 characters</name>
   <tag></tag>
   <elementGuidId>c31e0008-6143-410f-918b-3e8973712d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Name must be between 3 and 32 characters!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8618d842-99e3-4dbf-bde8-bdc69a1525e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-name</value>
      <webElementGuid>afc7d05f-c5c4-4a49-a1ec-799c8eb93a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invalid-feedback d-block</value>
      <webElementGuid>57c44926-8109-4717-b63f-739260dd5440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name must be between 3 and 32 characters!</value>
      <webElementGuid>cc3430b0-46d5-476f-b9e4-b41eb79d23ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-name&quot;)</value>
      <webElementGuid>c8832f2b-32f8-4e23-a84c-f0c408015e12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-name']</value>
      <webElementGuid>d7e21ced-674f-48b7-b89d-ad7c8eea4c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-contact']/fieldset/div/div/div</value>
      <webElementGuid>dbd8a73b-2056-4218-89dd-64fd1c409636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Name'])[1]/following::div[2]</value>
      <webElementGuid>b4d82924-1773-4e1b-9295-48146c689fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::div[3]</value>
      <webElementGuid>ea177c83-bc19-41bb-9dc6-12a3d83a0321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail Address'])[1]/preceding::div[1]</value>
      <webElementGuid>1ee84027-4ccf-4aff-9064-cb56718974df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail Address does not appear to be valid!'])[1]/preceding::div[1]</value>
      <webElementGuid>37751a31-8692-414e-8c90-022db3cdcbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name must be between 3 and 32 characters!']/parent::*</value>
      <webElementGuid>e967b9f9-fd35-49d6-9584-b458ac013cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div</value>
      <webElementGuid>6866456e-5812-41f2-b15b-c2d4c06fe1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-name' and (text() = 'Name must be between 3 and 32 characters!' or . = 'Name must be between 3 and 32 characters!')]</value>
      <webElementGuid>15b6e66c-631a-4ec4-b119-852170b8e0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
