<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-Mail Address does not appear to be valid</name>
   <tag></tag>
   <elementGuidId>6aa4f082-310a-4812-b72e-5e866e6dc85d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;E-Mail Address does not appear to be valid!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab1fac26-bc53-44d6-aa0b-cece5ff44b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-email</value>
      <webElementGuid>cdc96151-986a-4d06-b448-b6acd1b0f7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invalid-feedback d-block</value>
      <webElementGuid>55182736-f4f6-454b-826b-f379fa177560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Mail Address does not appear to be valid!</value>
      <webElementGuid>37c7b442-46c1-40b9-a147-69e151dcaa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-email&quot;)</value>
      <webElementGuid>c9891a98-d133-4040-97fe-25e04604c3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-email']</value>
      <webElementGuid>337fd1e0-a613-47c8-9170-fc435c916592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-contact']/fieldset/div[2]/div/div</value>
      <webElementGuid>da457cc5-f5d5-4c76-b08b-294508243b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Mail Address'])[1]/following::div[2]</value>
      <webElementGuid>bcd27ddf-5c2a-4954-8530-09f7a167e855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name must be between 3 and 32 characters!'])[1]/following::div[3]</value>
      <webElementGuid>8837b669-cb72-4ab4-a6a0-1eac013d0740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enquiry'])[1]/preceding::div[1]</value>
      <webElementGuid>07186f6b-3b02-4972-be84-d927d4f8cfd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[4]</value>
      <webElementGuid>4008cc0e-3c2c-43db-802a-0a636922dbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-Mail Address does not appear to be valid!']/parent::*</value>
      <webElementGuid>a89864fc-0eed-4a9d-9c58-1c33658f4528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div</value>
      <webElementGuid>cc2d263a-a551-4537-8567-59363af83179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-email' and (text() = 'E-Mail Address does not appear to be valid!' or . = 'E-Mail Address does not appear to be valid!')]</value>
      <webElementGuid>6987cab7-4823-45ad-8daa-cbe18c276c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
