<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Show All MP3 Players_fas fa-home</name>
   <tag></tag>
   <elementGuidId>3f415be6-974f-48ce-b493-86cb11778098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='information-contact']/ul/li/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3f3be542-ecb7-4734-af30-f2a0a26d5588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-home</value>
      <webElementGuid>2ae68475-c748-4c76-9693-e4d1fd9d96f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;information-contact&quot;)/ul[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[1]/i[@class=&quot;fas fa-home&quot;]</value>
      <webElementGuid>e7a27afb-810a-4a60-a34b-0cc96b247ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='information-contact']/ul/li/a/i</value>
      <webElementGuid>8ec0aaf4-d94b-481e-b4b2-e49c1d783082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/ul/li/a/i</value>
      <webElementGuid>45058617-5b59-4be7-815e-3a8f038e9106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
