<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enquiry_enquiry</name>
   <tag></tag>
   <elementGuidId>efb1ce5a-97ca-4b7a-b23c-9c01c6189af0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-enquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-enquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enquiry&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9e55a710-c092-40d0-9c8b-97886634164b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enquiry</value>
      <webElementGuid>2f063e62-651f-44a9-b21e-171031632924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>276ce92b-3308-46e1-995f-7ea193e8fc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-enquiry</value>
      <webElementGuid>d1b3d797-1c8f-478e-8860-d1460d4a5872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ab3e974-8121-4800-8edc-bf061f8725e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-enquiry&quot;)</value>
      <webElementGuid>bc7b02b6-5f92-4c37-bb89-1a3035f3971d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-enquiry']</value>
      <webElementGuid>dca79ca6-30ac-48fe-b9ab-79f3df41c2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-contact']/fieldset/div[3]/div/textarea</value>
      <webElementGuid>9c8b610d-ea00-4465-a194-17625fca09f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>641da5e5-e3e8-4ea8-a90c-18cfd38cb072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'enquiry' and @id = 'input-enquiry']</value>
      <webElementGuid>0965e5f6-823a-49cc-bed4-2e618b52e17b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
