<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Atlanta, Georgia, United States</name>
   <tag></tag>
   <elementGuidId>a12e6f5d-f461-4c72-91d8-ec5db323bc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-suggestion-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;option-0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>583f1189-208f-43e0-9820-b4121fffadb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>684700c8-923a-4f3a-97c8-5cda135cad04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e6757b1f-951b-4b9f-83da-a54837b635f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>562d0fee-f471-4362-9bbc-9d5a1b00f268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fd3f115-1616-4fde-a34a-f8d9a8a0fe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>2b44c9c6-ce21-42ee-a9e6-d1b513770596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prefix</name>
      <type>Main</type>
      <value>SYSTEM_LOCATION_STROKED</value>
      <webElementGuid>f3ff6f73-99b8-4c0c-b052-4d6f7505eee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c569q9j atm_r2_1j28jx2 atm_5j_kitwna atm_9j_tlke0l atm_9s_1txwivl atm_cx_exct8b atm_gw_1rrn7iu atm_l8_ftgil2 atm_kd_glywfm_1w3cfyq atm_uc_aaiy6o_1w3cfyq atm_26_1qwqy05_1w3cfyq atm_70_6ezzhz_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_pfnrn2_1oszvuo atm_26_1qwqy05_pfnrn2_1oszvuo atm_70_6ezzhz_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_26_jk66pa_1nos8r_uv4tnr atm_26_jk66pa_csw3t1 c16b4zta atm_26_jk66pa dir dir-ltr</value>
      <webElementGuid>7cd90e3f-86a3-4099-986e-61b01b4a8f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atlanta, Georgia, United States</value>
      <webElementGuid>d7143a20-7ae7-4d9b-856b-2e0577b03f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-suggestion-0&quot;)</value>
      <webElementGuid>52499a27-fbce-47ee-b1a1-5d2c77fecb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      <webElementGuid>d52358fe-0f9c-4582-9f0f-cdc527e23409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-listbox']/div</value>
      <webElementGuid>14c0f9b4-e1d3-418b-b116-8cd1c501fe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::div[5]</value>
      <webElementGuid>d9a8e2c5-023f-4134-a12b-d53efa881ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experiences'])[1]/following::div[11]</value>
      <webElementGuid>a951ab58-4ca2-4732-b898-f8be5601bda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>79052448-50b1-4659-bb14-7dde3cd53560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bigsearch-query-location-suggestion-0' and (text() = 'Atlanta, Georgia, United States' or . = 'Atlanta, Georgia, United States')]</value>
      <webElementGuid>9408c889-b99c-4146-9c52-ab542ff2c1f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
