<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3 days</name>
   <tag></tag>
   <elementGuidId>0f4a7beb-7d59-41d7-a055-7113d571a986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='micro-flex-chips-']/div/label[4]/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;3 days&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b92dfa6-6a2b-43f3-9837-9c8ce2d789b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6949e366-bb7f-4f4e-a3a1-1241e03e70d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 days</value>
      <webElementGuid>188d0a9d-defa-4776-8839-afa33b7f0d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;micro-flex-chips-&quot;)/div[@class=&quot;h1hdfvnt atm_p9_glywfm atm_9s_glywfm_14pyf7n c1wlfnvs atm_l0_1wugsn5 atm_vv_1q9ccgz atm_9s_1txwivl atm_cx_19bvopo a1uny8fd atm_l8_kysjoz dir dir-ltr&quot;]/label[@class=&quot;c1ef8kub atm_9j_tlke0l atm_r3_1h6ojuz atm_3f_uuagnh atm_l8_idpfg4 atm_gi_idpfg4 atm_2d_1qwqy05 atm_4b_rke8ap atm_7l_jt7fhx atm_bx_48h72j atm_mk_h2mmj6 atm_uq_17liqq3 atm_ui_1bljbuh atm_uv_xoomkg atm_kd_glywfm atm_lo_evh4rp atm_le_evh4rp atm_j6_1vi7ecw atm_5j_qe0vi4 atm_c8_1uc0753 atm_g3_lonqig atm_fr_r7vles atm_lk_dlk8xv atm_ll_dlk8xv atm_7l_177r58q_1nos8r_uv4tnr atm_4b_lb1gtz_1nos8r_uv4tnr atm_7l_177r58q_csw3t1 atm_4b_lb1gtz_csw3t1 atm_tr_ybgkrq_csw3t1 atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_uc_aaiy6o_1w3cfyq atm_70_15w7q17_1w3cfyq atm_uc_glywfm_1w3cfyq_1rrf6b5 atm_uc_aaiy6o_pfnrn2_1oszvuo atm_70_15w7q17_pfnrn2_1oszvuo atm_uc_glywfm_pfnrn2_1o31aam atm_uc_aaiy6o_1s76pf2 atm_70_15w7q17_1s76pf2 atm_uc_glywfm_1s76pf2_1rrf6b5 atm_uc_aaiy6o_1y5fnfe_1oszvuo atm_70_15w7q17_1y5fnfe_1oszvuo atm_uc_glywfm_1y5fnfe_1o31aam c1s1ko7x cg3b11m atm_9s_116y0ak atm_h_1h6ojuz dir dir-ltr&quot;]/span[@class=&quot;mp7a7yt atm_9s_1ulexfb dir dir-ltr&quot;]/span[1]</value>
      <webElementGuid>0d9171d7-6ad4-465c-9002-c27a561ed4fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='micro-flex-chips-']/div/label[4]/span[2]/span</value>
      <webElementGuid>068963e5-75b0-422a-830f-3e67c043ef44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±2 days'])[1]/following::span[3]</value>
      <webElementGuid>386ccccc-732e-4658-bfa3-dc1f1d15f3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±1 day'])[1]/following::span[7]</value>
      <webElementGuid>0523460f-a19b-468e-ac50-23150fd2862a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±3 days'])[1]/preceding::span[1]</value>
      <webElementGuid>0725ef86-391f-4f3c-b5ce-09f11aef6395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±7 days'])[1]/preceding::span[4]</value>
      <webElementGuid>ef350d1e-f74a-462b-ab16-9b22f5773c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3 days']/parent::*</value>
      <webElementGuid>fa8dac16-91ce-420d-9965-40b9f668a593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/span[2]/span</value>
      <webElementGuid>2ff57ed6-7702-4b33-ae3f-2c32be53690f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3 days' or . = '3 days')]</value>
      <webElementGuid>7b8d4773-0d42-48d9-9438-b5f9dfb17921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
