<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Row 2 was saved</name>
   <tag></tag>
   <elementGuidId>025ead58-73bc-4d4e-be66-3f580f543a2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Row 2 was saved&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e5408c1-ec80-4014-9de6-e74d7204a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmation</value>
      <webElementGuid>7e7a53ac-d711-42d5-9c5b-faedc914b725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Row 2 was saved</value>
      <webElementGuid>dc7039b6-5b3e-4e5d-a6a4-4930f01f693c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmation&quot;)</value>
      <webElementGuid>492707e4-457c-4ebf-9592-f7ae32bbc582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='confirmation']</value>
      <webElementGuid>bdd4fb1a-a20f-4227-9aef-9b4f8377f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rows']/div[4]</value>
      <webElementGuid>00629613-0a27-4268-bcac-b7e1da254821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::div[1]</value>
      <webElementGuid>c78120c6-592b-48f2-9457-6ffdc3b64c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::div[1]</value>
      <webElementGuid>c7781381-b801-4aea-ba8f-b13a133091e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test case 1: NoSuchElementException'])[1]/preceding::div[1]</value>
      <webElementGuid>b124a9d7-d3a6-48d3-9cef-0bc3a6f6670b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open page'])[1]/preceding::div[1]</value>
      <webElementGuid>9817d6ce-9aaf-47cb-8791-318cee21164c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Row 2 was saved']/parent::*</value>
      <webElementGuid>edb721f3-b556-4468-ba62-d0ef565c353e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>f8d810ec-4292-4272-b0b7-51cf9ed9b699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'confirmation' and (text() = 'Row 2 was saved' or . = 'Row 2 was saved')]</value>
      <webElementGuid>09caad4e-4bca-4c80-8d96-5a4afb849b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
