<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Email_a-osi3l72k7skm</name>
   <tag></tag>
   <elementGuidId>a8f98993-d31f-4605-a0ad-b8bde93ff1c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-osi3l72k7skm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-osi3l72k7skm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-osi3l72k7skm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>45acb770-edd5-4ced-82a0-8f131e841190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>787f6dc1-d3ee-4c1d-8cb1-645fc80b37ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>d484139e-e077-469e-a23f-824b12294fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>7c5cb390-f36a-4880-a89a-530f30b88bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a0660050-804f-4dc0-bbcf-3d72b413d309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-osi3l72k7skm</value>
      <webElementGuid>421cf528-a534-4bf0-8f9c-cfa5afe4611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>acc2d44f-9bf5-4545-a003-4178a97b75cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e5d5e8c8-a6e0-465f-a89b-4f7cd1bae3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>85407085-4c7a-4f41-8a3f-f79ab39f108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcZIMMcAAAAAAC-6Ee4dXQRHziIJEWxvZYNPGyk&amp;co=aHR0cHM6Ly9wcmFjdGljZXRlc3RhdXRvbWF0aW9uLmNvbTo0NDM.&amp;hl=en&amp;v=rW64dpMGAGrjU7JJQr9xxPl8&amp;size=normal&amp;cb=h31xdz6yy2eo</value>
      <webElementGuid>756b5a27-63a6-46e4-bbb3-4855a4b2f54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-form-161&quot;)/div[@class=&quot;wpforms-recaptcha-container wpforms-is-recaptcha wpforms-is-recaptcha-type-v2&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>2174fb69-933d-426f-bb4f-759d7a9cbaf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-osi3l72k7skm']</value>
      <webElementGuid>06566efa-06ac-4f96-b6fb-144810d6e44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='wpforms-form-161']/div[4]/div/div/div/iframe</value>
      <webElementGuid>ee61dc7c-2601-4906-801a-db081347d231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>34e3ee37-e647-4736-bf0b-9e3d40b6f129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-osi3l72k7skm' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcZIMMcAAAAAAC-6Ee4dXQRHziIJEWxvZYNPGyk&amp;co=aHR0cHM6Ly9wcmFjdGljZXRlc3RhdXRvbWF0aW9uLmNvbTo0NDM.&amp;hl=en&amp;v=rW64dpMGAGrjU7JJQr9xxPl8&amp;size=normal&amp;cb=h31xdz6yy2eo']</value>
      <webElementGuid>15052e62-fa92-487d-9f37-3a306868a300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
