<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First_wpformsfields0last</name>
   <tag></tag>
   <elementGuidId>c1226ce4-7971-4920-b0ad-aaf92ab0c2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_0-last</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-161-field_0-last']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>743ee861-ceb9-495e-b109-63768d1d1324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d95244eb-818e-4d52-88b2-ec8544c8c642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_0-last</value>
      <webElementGuid>127dd1c2-b7aa-4f32-87c8-636e60ae2777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-name-last wpforms-field-required wpforms-error</value>
      <webElementGuid>801a9baa-2568-4b4e-aa8d-a75ed152991c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][0][last]</value>
      <webElementGuid>8e191fde-2f55-46e4-8560-5c873a5da526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_0-last&quot;)</value>
      <webElementGuid>954b6a9d-a253-4580-a38a-246f1bfa19e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-161-field_0-last']</value>
      <webElementGuid>b25fe380-0650-49b7-a4b0-a3f778ebecb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_0-container']/div/div[2]/input</value>
      <webElementGuid>db306aaa-bf95-47b2-b58d-2bd65cec3407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>e5ea3ed6-29b4-46ef-8255-338614216ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wpforms-161-field_0-last' and @name = 'wpforms[fields][0][last]']</value>
      <webElementGuid>270ca368-c7e0-4b29-9e01-3e07de4b9b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
