<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wpformsfields1</name>
   <tag></tag>
   <elementGuidId>f564b1da-ef4a-46d8-bb53-b15da1d8ec32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-161-field_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4edf9b-1de2-48a2-99b2-bcaca215eb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9526f862-3813-4ea0-aed8-51f4d676559b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_1</value>
      <webElementGuid>ed2e2751-f350-4edc-beaa-ee963437ca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required wpforms-error</value>
      <webElementGuid>a51a297e-df4c-4a65-9a16-b75a47a2a95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>8df26c36-b053-4556-a676-33c40a7b179b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ecaa092e-b566-47c6-9218-40a0d00d85cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c36950d4-740b-49b4-8db3-81b63aeda6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_1&quot;)</value>
      <webElementGuid>aa1f9391-7e48-4275-b3e6-9ed295be36df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-161-field_1']</value>
      <webElementGuid>a598773a-cbfb-4fb6-8f52-51493fb54820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_1-container']/input</value>
      <webElementGuid>78434be2-a227-4888-9bc5-6ae59a61f96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>e6fd1900-dfe2-46df-a615-c5320a30e697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wpforms-161-field_1' and @name = 'wpforms[fields][1]']</value>
      <webElementGuid>b528f6fe-c95f-43a6-90c0-9eb103c57d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
