<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required_1</name>
   <tag></tag>
   <elementGuidId>914d2a56-c78a-4f18-9c6d-f834eeff7fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_0-last-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='wpforms-161-field_0-last-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#wpforms-161-field_0-last-error</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>75ef3d97-50ac-473c-a1fd-57b875592dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_0-last-error</value>
      <webElementGuid>bf41f353-2ddd-4677-8886-635ead6e220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-error</value>
      <webElementGuid>5a15b331-9159-4bbc-a0a1-3a9227f7dfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>wpforms-161-field_0-last</value>
      <webElementGuid>327e2919-3789-4ab3-b8e4-7b5d4c624ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>4c755ee2-9a5c-480b-8e45-953077837c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_0-last-error&quot;)</value>
      <webElementGuid>ce07b58f-13c3-4a8f-a98f-f5342d7bb868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='wpforms-161-field_0-last-error']</value>
      <webElementGuid>0b9fb804-c8ce-43d3-9d67-13ef48d355e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_0-container']/div/div[2]/label[2]</value>
      <webElementGuid>3c5253e3-645f-4b06-bcad-c0f8e05f74a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last'])[1]/following::label[1]</value>
      <webElementGuid>871cd83a-fe50-4cde-99ed-60e6268e5ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/following::label[2]</value>
      <webElementGuid>f0e1421d-cc2d-4947-ab5e-efad2fe3297f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::label[1]</value>
      <webElementGuid>75e892c5-4d7e-4758-8fdd-76828f56bd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/label[2]</value>
      <webElementGuid>cfce5f9b-a33a-4bcf-ba0e-1731b78773ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'wpforms-161-field_0-last-error' and (text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>6b839e18-cdfe-4a95-944b-c0946c0dea65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
