<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Google reCAPTCHA verification failed,_ca1802</name>
   <tag></tag>
   <elementGuidId>7a5e8e03-6b23-4510-b434-050b829500f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-field_recaptcha-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='wpforms-field_recaptcha-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Google reCAPTCHA verification failed, please try again later.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>79e64787-eb64-48ac-b00b-9991d11fe5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-field_recaptcha-error</value>
      <webElementGuid>ac3ca6ad-1f9a-48a9-81ba-465b2a771178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-error</value>
      <webElementGuid>fbe8caf2-1a2d-4172-a763-c78d6c64fc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google reCAPTCHA verification failed, please try again later.</value>
      <webElementGuid>c93fa88c-fab5-482a-bd1f-c2409b9ec16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-field_recaptcha-error&quot;)</value>
      <webElementGuid>72c472cb-3395-480e-845a-0a6ef5d23e59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='wpforms-field_recaptcha-error']</value>
      <webElementGuid>2a66b0fc-671a-478a-91c1-07c9f5ee9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='wpforms-form-161']/div[4]/label</value>
      <webElementGuid>c9384069-45cf-4c93-8b90-cbf393f41bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>ed54a811-3341-4850-bcee-eac840299ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is Test Message'])[1]/following::label[2]</value>
      <webElementGuid>3940ea3b-1a48-46e8-a7e4-1eba09bf4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>8009996e-b6fb-4b98-9118-9d36446af947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google reCAPTCHA verification failed, please try again later.']/parent::*</value>
      <webElementGuid>ba30489e-a7d3-451f-b308-2686899436c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>00e1da44-2d6f-47b9-885b-ef939fa8c7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'wpforms-field_recaptcha-error' and (text() = 'Google reCAPTCHA verification failed, please try again later.' or . = 'Google reCAPTCHA verification failed, please try again later.')]</value>
      <webElementGuid>06044815-260d-4655-bd60-55abacc64e02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
