<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_iPhone_1</name>
   <tag></tag>
   <elementGuidId>3bffcae7-5201-44dc-8084-2ab8e617b36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-cart']/div/ul/li/table/tbody/tr[2]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.text-start > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#header-cart >> internal:text=&quot;iPhone&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b029cd9d-87a6-4932-a8bc-ea32ffe6923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.opencart.com/en-gb/product/iphone</value>
      <webElementGuid>ff5848c2-1f71-4f64-81fe-f9db58ac05f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone</value>
      <webElementGuid>6722aa4e-4f04-491c-bf13-fb78b6a5abf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-cart&quot;)/div[@class=&quot;dropdown d-grid&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-end p-2 show&quot;]/li[1]/table[@class=&quot;table table-striped mb-2&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-start&quot;]/a[1]</value>
      <webElementGuid>c6f0441c-3035-418b-8c69-cc97a39bca24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-cart']/div/ul/li/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>2fbc7b29-7617-45c8-ad70-9e3e8b13a2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'iPhone')]</value>
      <webElementGuid>253a19d0-082d-4f58-bd91-2511ff8c6deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$122.00'])[1]/following::a[2]</value>
      <webElementGuid>35c4d84e-f116-479a-92f6-6e234bd538a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x 1'])[1]/following::a[2]</value>
      <webElementGuid>8c66b2da-3f00-4580-a351-b8e9c1113567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x 1'])[2]/preceding::a[1]</value>
      <webElementGuid>6386a752-4702-48d6-8ea2-49c9b6ed9d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$123.20'])[1]/preceding::a[1]</value>
      <webElementGuid>e2d0405b-00a3-4e88-8699-282b43c413c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iPhone']/parent::*</value>
      <webElementGuid>0a8a8a8b-bc1b-460e-96e6-13872fb85232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demo.opencart.com/en-gb/product/iphone')])[2]</value>
      <webElementGuid>769d8cf9-9a96-4e22-8f2d-494fe708b8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>4cc1e324-58b3-4712-a0fa-22e3735a1ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.opencart.com/en-gb/product/iphone' and (text() = 'iPhone' or . = 'iPhone')]</value>
      <webElementGuid>8cc72990-1613-4257-a4ff-349850713e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
