<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Success You have added HTC Touch HD to _9141cb</name>
   <tag></tag>
   <elementGuidId>dc02bda9-6de0-49a7-85a3-96c9a11a080f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alert']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-success.alert-dismissible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Success: You have added HTC Touch HD to your shopping cart!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cd7f7f5-d952-4789-9147-a9ea58c43d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success alert-dismissible</value>
      <webElementGuid>5c930b74-a073-4574-b52f-0e2a5b55dec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Success: You have added HTC Touch HD to your shopping cart! </value>
      <webElementGuid>0d282135-c3d3-4700-97a9-a7bb9a1eacb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert&quot;)/div[@class=&quot;alert alert-success alert-dismissible&quot;]</value>
      <webElementGuid>ab9d620f-3ab5-4e7b-a120-c42efb4ee3e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert']/div</value>
      <webElementGuid>1ed3c107-8605-4ab0-bdef-5df715ea15df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Success: You have added']/parent::*</value>
      <webElementGuid>bdc3adfd-d1e1-43b3-8994-aa8f3216f20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>23e9fa26-3045-4a7f-9051-ca5b2749dda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Success: You have added HTC Touch HD to your shopping cart! ' or . = ' Success: You have added HTC Touch HD to your shopping cart! ')]</value>
      <webElementGuid>7adbfa58-8c06-4b5c-81c4-1a01eaf4946d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
