<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ex Tax 100.00_fa-solid fa-shopping-cart</name>
   <tag></tag>
   <elementGuidId>e9ae7107-216e-4c96-803c-42f8c0e27bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/div/div/div[2]/form/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-shopping-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add to Cart&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a13c3634-3e11-44db-8bd4-0d4a66473a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-shopping-cart</value>
      <webElementGuid>0e35bb92-95f9-41ac-8d56-6d153ac4028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;col mb-3&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;content&quot;]/form[1]/div[@class=&quot;button-group&quot;]/button[1]/i[@class=&quot;fa-solid fa-shopping-cart&quot;]</value>
      <webElementGuid>6dd2ae1a-a334-4d9d-b7a8-be968e167d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/div/div/div[2]/form/div/button/i</value>
      <webElementGuid>dcc25098-de32-496e-b5a8-30c8d5549456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button/i</value>
      <webElementGuid>509c99f5-cd9d-4fae-8b87-01f5b2a63de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
