<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ProjectActivity23Mon24Tue25Wed26Thu27_031cee</name>
   <tag></tag>
   <elementGuidId>ff9e4027-db8c-4e73-b586-75c9891025e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/form/div[2]/table</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.orangehrm-timesheet-table.--editable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ProjectActivity23Mon24Tue25Wed26Thu27Fri28Sat29SunProjectAdministrationAdd Row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
      <webElementGuid>96d560b7-a062-41f3-8f8c-49055f19fdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-timesheet-table --editable</value>
      <webElementGuid>1b7a3bca-b69b-47c8-ab65-e08d4b52de43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProjectActivity23Mon24Tue25Wed26Thu27Fri28Sat29SunProjectAdministrationAdd Row</value>
      <webElementGuid>a314c854-cd17-4aeb-9fb3-5add5fecfce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/form[@class=&quot;oxd-form orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-timesheet-body&quot;]/table[@class=&quot;orangehrm-timesheet-table --editable&quot;]</value>
      <webElementGuid>c7fce212-5951-4ab0-97e1-11f40418cf86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/form/div[2]/table</value>
      <webElementGuid>b07e13c4-bead-4017-ad72-c2463841177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Info'])[1]/following::table[1]</value>
      <webElementGuid>367aa1c6-0adb-46c7-82ee-d3b445521aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table</value>
      <webElementGuid>f8080ff8-495d-4425-9190-424bfee56d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//table[(text() = 'ProjectActivity23Mon24Tue25Wed26Thu27Fri28Sat29SunProjectAdministrationAdd Row' or . = 'ProjectActivity23Mon24Tue25Wed26Thu27Fri28Sat29SunProjectAdministrationAdd Row')]</value>
      <webElementGuid>57b69957-f3ff-4298-ab7b-6d57241f9f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
