<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Loading_mfp-arrow mfp-arrow-right mf_6e5f20</name>
   <tag></tag>
   <elementGuidId>b7f4844b-6d44-487e-aec5-6fa6e44f6e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mfp-arrow.mfp-arrow-right.mfp-prevent-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next (Right arrow key)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f91f8ea-132c-4d64-9f7b-1f4d782e8db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next (Right arrow key)</value>
      <webElementGuid>b303be11-5115-4ac1-8353-5fa30c8768f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1cc37ec8-77c1-4bd4-98a3-9408ecf15938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mfp-arrow mfp-arrow-right mfp-prevent-close</value>
      <webElementGuid>eaaec4c0-6b08-4e38-9831-59e8b6cfd62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mfp-zoom-out-cur&quot;]/div[@class=&quot;mfp-wrap mfp-gallery mfp-close-btn-in mfp-auto-cursor mfp-ready&quot;]/div[@class=&quot;mfp-container mfp-image-holder mfp-s-ready&quot;]/button[@class=&quot;mfp-arrow mfp-arrow-right mfp-prevent-close&quot;]</value>
      <webElementGuid>e76f2d27-c6a9-4b44-b0ef-4e06b51277ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>6d4f96de-0ce4-4d17-b16f-77cc4acf781a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9cacb203-795f-4345-af36-659e203b225c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Next (Right arrow key)' and @type = 'button']</value>
      <webElementGuid>10df1204-b7b9-4202-9758-a449e5d50b9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
