<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In_1</name>
   <tag></tag>
   <elementGuidId>45f5eade-e797-4ecb-8284-7bfd1ce7aebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.account-management > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='global-header']/div[2]/ul/li[2]/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Log In&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bb48602-919a-4ea6-b1bd-b35f7e827169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-affiliatename</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>c9cae1ec-da6b-42fc-9d5f-042802aca79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>edd844ab-38b7-47a2-b8dd-3fa065cc3366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regformid</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>6bc93423-0d24-43b4-b831-0abba87f07cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tref</name>
      <type>Main</type>
      <value>/members/v3_1/login</value>
      <webElementGuid>f26dd34c-ab44-44ac-adbf-047c1a41ad96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behavior</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>07ca1c64-1ffe-48f6-a103-e8852ac5f240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>65e1eb32-cd6a-4987-af1f-666124bc1105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5885bc32-6feb-4721-a8d6-9d0986f2baaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>77f77fd3-59fb-4d51-a747-26f147b4ec46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[@class=&quot;container&quot;]/ul[@class=&quot;tools focused&quot;]/li[@class=&quot;user hover&quot;]/div[@class=&quot;global-user&quot;]/div[@class=&quot;global-user-container&quot;]/ul[@class=&quot;account-management&quot;]/li[3]/a[1]</value>
      <webElementGuid>279bcb58-0fdf-417b-818a-0a0e23ce0177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='global-header']/div[2]/ul/li[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>6184c35f-1a82-4721-88da-8e839229c804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Log In')])[2]</value>
      <webElementGuid>14eedb93-eac5-4153-8c8f-2f1bdd7640d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Settings'])[1]/following::a[1]</value>
      <webElementGuid>aa798f42-7087-4a8b-bb5b-727d7b9353d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome!'])[1]/following::a[2]</value>
      <webElementGuid>bea2ade1-d10e-47ea-99dc-af1324bb2cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourites'])[1]/preceding::a[1]</value>
      <webElementGuid>197dd269-5abe-4070-a19f-742c6d2b434e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Football'])[1]/preceding::a[4]</value>
      <webElementGuid>ba9dfcfe-d116-4178-9672-6bf74cb304de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[30]</value>
      <webElementGuid>054f075b-4630-4f75-9f1b-ecd3d603f619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>410fb966-1f51-438a-a581-2efb35be7213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>1fa019b2-40ab-4f44-aea1-d09b9e324f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
