<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Follow_1_2</name>
   <tag></tag>
   <elementGuidId>c15d218f-a115-43d1-8528-fa27b0e9bfa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section/div/ul/li[15]/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Mumbai IndianscricketFollow&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04b09cd0-00d0-43c7-9241-318dee837ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Button--sm Button--alt</value>
      <webElementGuid>14ac17b2-8d9e-4849-83a9-ec11b57f541a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>834b896b-16f3-4b92-add8-4bd51cb584da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-event_detail</name>
      <type>Main</type>
      <value>manage-favorites:follow:mumbai indians</value>
      <webElementGuid>a514c360-895a-4cda-94e3-15266720a025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-event_name</name>
      <type>Main</type>
      <value>module interaction</value>
      <webElementGuid>56ac4bd2-24b9-4429-aa25-87c12fc83f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-playerteamdetail</name>
      <type>Main</type>
      <value>Mumbai Indians</value>
      <webElementGuid>6d220522-e3bc-48b5-81ac-b9ded836a222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-section</name>
      <type>Main</type>
      <value>frontpage</value>
      <webElementGuid>8bb0ab9d-1bf7-45eb-b1d6-8932bc08755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-basemetrics</name>
      <type>Main</type>
      <value>swid</value>
      <webElementGuid>ccc6cc79-8fc6-4f75-9d94-9208f4161b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-site</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>83e9d8d8-ac17-44f5-a570-6a16b1b0ac7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track-content_type</name>
      <type>Main</type>
      <value>favorites</value>
      <webElementGuid>05634304-2fa0-4b4e-a6d5-14847ff5dd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>categorytype</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c9ec46dc-13c9-4057-a918-8bfd36a81a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow</value>
      <webElementGuid>fe451e33-5b09-4b5e-a4e3-8a17ed40a2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fittPortal_0&quot;)/div[@class=&quot;bp-mobile bp-mobileLG bp-mobileTablet bp-mobileMDPlus bp-mobileLGPlus no-touch&quot;]/div[@class=&quot;lightbox__wrapper flex justify-center lightbox__wrapper--mobile LightBox&quot;]/section[@class=&quot;lightbox__contentBox overflow-hidden relative lightbox__contentBox--heightWebkit lightbox__contentBox--mobile&quot;]/div[@class=&quot;lightbox__content lightbox__content--mobile&quot;]/div[@class=&quot;ResponsiveWrapper&quot;]/section[@class=&quot;Card FavMgmt FavMgmt--tabletPlus&quot;]/div[@class=&quot;Wrapper Card__Content&quot;]/section[@class=&quot;FavMgmt__Pane flex justify FavMgmt__Pane--searching&quot;]/section[@class=&quot;FavMgmt__Col FavMgmt__Col--Left flex flex-column&quot;]/div[@class=&quot;FavMgmt__Wrapper br2 flex-auto&quot;]/ul[@class=&quot;FavMgmt__Section&quot;]/li[@class=&quot;FavMgmt__Item flex items-center&quot;]/div[@class=&quot;FavMgmt__Item__Remove flex-none self-stretch flex items-center justify-center ph4&quot;]/div[@class=&quot;fitt-tracker&quot;]/button[@class=&quot;Button Button--sm Button--alt&quot;]</value>
      <webElementGuid>436799e6-9383-4a55-87d7-e50822362310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , favorites-manager-ifra_846b91</value>
      <webElementGuid>23ed8117-9917-4e9a-bd9c-a72525d7ed49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section/div/ul/li[15]/div[2]/div/button</value>
      <webElementGuid>b033c980-65c4-4052-8a01-31e881ef75e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cricket'])[3]/following::button[1]</value>
      <webElementGuid>3b4b19e4-26f5-4678-9942-dce617ce35dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai Indians'])[1]/following::button[1]</value>
      <webElementGuid>e491b412-d968-4b35-9838-50c22ff4ab1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Southern Indiana Screaming Eagles'])[2]/preceding::button[1]</value>
      <webElementGuid>eec98ac1-3961-453f-b339-6f9195862412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ncaaw'])[4]/preceding::button[1]</value>
      <webElementGuid>bcace26b-2029-4ed1-8317-01de05fcfdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/div[2]/div/button</value>
      <webElementGuid>2db7109f-4cfc-4ba8-935d-023da721dc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Follow' or . = 'Follow')]</value>
      <webElementGuid>23408cc0-db50-4498-b165-a20b214c13f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
