<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log In</name>
   <tag></tag>
   <elementGuidId>db84e9f2-9d43-42d6-b781-288c05c05795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BtnSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BtnSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;BtnSubmit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3eb7ff2d-6d4f-4ddc-9c2b-96279bba3575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>&amp;lpos=customize:espn:oneid:module:login</value>
      <webElementGuid>c9a0c033-f3f0-481b-9c4e-5a8e4a5020b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-submit btn-primary</value>
      <webElementGuid>cddbaf39-f79a-40d6-b7b5-1a160f7042e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-route</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75b14fda-0559-42fe-b46b-ff60385ad6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behavior</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>233fddd6-6dd6-4efe-8546-cd1028138e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tref</name>
      <type>Main</type>
      <value>/members/v3_1/login</value>
      <webElementGuid>9105504e-5268-4df5-8d78-7eb064ddda83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regformid</name>
      <type>Main</type>
      <value>espn_bbc</value>
      <webElementGuid>edf91b38-66c8-4592-b3bc-6fe7e5a927d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>7aff58ac-ba7c-4bb9-b49c-0da2875e2d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-affiliatename</name>
      <type>Main</type>
      <value>espn</value>
      <webElementGuid>48e7f6dc-a66b-4232-831c-7b8ca74cd488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>e0d68686-727a-41b3-8b0c-c0ab7dc1f9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BtnSubmit&quot;)</value>
      <webElementGuid>78071002-095c-4048-ba66-39b3a6fd0417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ebb9260d-55d3-4799-84ab-b51c19f80254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BtnSubmit</value>
      <webElementGuid>e5e75efe-f5cd-44ce-9d8c-ee66d196ff61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>BtnSubmit</value>
      <webElementGuid>cbc9fbb7-4c67-4fe4-8eec-0ae66303af72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>acdb1358-3da3-45d4-9fa8-05f756f9a15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>d99f03fe-037e-4581-90db-7a9f4058c3ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='BtnSubmit']</value>
      <webElementGuid>d2f4ad75-6aa9-43ca-b9a7-9c8b8aa88d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BtnSet-wrapper']/button</value>
      <webElementGuid>d0fcc346-b11b-407c-9c7b-8da6ed9e9250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swan@abc.com'])[1]/following::button[2]</value>
      <webElementGuid>4558a7e1-5df6-40d4-b25e-0df283d99b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good news! You already have a MyDisney account'])[1]/following::button[2]</value>
      <webElementGuid>dfbc4cb5-6fcb-4212-98ec-bc28b6716b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more about MyDisney'])[1]/preceding::button[1]</value>
      <webElementGuid>596d3754-17b3-40a0-a4d9-e3b7a8ae1a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPN is part of The Walt Disney Family of Companies.'])[1]/preceding::button[2]</value>
      <webElementGuid>da6a72c6-4f6d-4cbd-88ca-b7b7ac29fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>113564ac-899e-445c-ac21-dfd37a828c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>4f349d1d-12fd-4cb2-b952-91756722fd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'BtnSubmit' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>66b65d5c-082c-41aa-95b6-4046bd58a691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='&amp;lpos=customize:espn:oneid:module:login']</value>
      <webElementGuid>f8c18d8c-c696-4fad-91d2-d458ff4ea382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='sideLogin-left-rail']/button[2]</value>
      <webElementGuid>8713bf46-7dde-4cc8-9403-33ac1a00df31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Account'])[3]/following::button[1]</value>
      <webElementGuid>14435812-2098-4966-a6a3-0e69b90a0d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customise ESPN'])[1]/following::button[2]</value>
      <webElementGuid>8cbfb22a-567c-4ab8-84b4-0f77574e30ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured'])[1]/preceding::button[1]</value>
      <webElementGuid>f3ec43f5-6a31-4c65-9859-1683a7394e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paris Olympics'])[1]/preceding::button[1]</value>
      <webElementGuid>1028bd3a-5951-48b8-ae7e-9103fd0bc915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/button[2]</value>
      <webElementGuid>6509b66a-98fb-4c5b-8e88-1166ed80f008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '&amp;lpos=customize:espn:oneid:module:login' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>2c9f3586-499e-413f-96d8-d57889bbe249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
