<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear</name>
   <tag></tag>
   <elementGuidId>57ef1390-6cf5-4530-b1ec-44374cdf4a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TypeaheadControls__Clear.TypeaheadControls__Clear--text.n8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Clear&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2315d834-65a7-475c-8f22-6e0c11034120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TypeaheadControls__Clear TypeaheadControls__Clear--text n8</value>
      <webElementGuid>905e2b40-13a4-4ded-ab3d-188a5824a130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>141b91b2-9499-465c-bfe7-8d5ab2aa1469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fittPortal_0&quot;)/div[@class=&quot;bp-mobile bp-mobileLG bp-mobileTablet bp-mobileMDPlus bp-mobileLGPlus no-touch&quot;]/div[@class=&quot;lightbox__wrapper flex justify-center lightbox__wrapper--mobile LightBox&quot;]/section[@class=&quot;lightbox__contentBox overflow-hidden relative lightbox__contentBox--heightWebkit lightbox__contentBox--mobile&quot;]/div[@class=&quot;lightbox__content lightbox__content--mobile&quot;]/div[@class=&quot;ResponsiveWrapper&quot;]/section[@class=&quot;Card FavMgmt FavMgmt--tabletPlus&quot;]/div[@class=&quot;Wrapper Card__Content&quot;]/section[@class=&quot;FavMgmt__Pane flex justify FavMgmt__Pane--searching&quot;]/div[@class=&quot;FavMgmt__Pane__Search&quot;]/div[@class=&quot;form__group cf ma0 mb3 flex-shrink form__group--search&quot;]/div[@class=&quot;Typeahead__Wrapper hasControls&quot;]/div[@class=&quot;TypeaheadControls absolute&quot;]/div[@class=&quot;TypeaheadControls__Clear TypeaheadControls__Clear--text n8&quot;]</value>
      <webElementGuid>6415c735-4799-449b-a449-7cf03ef2e9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , favorites-manager-ifra_846b91</value>
      <webElementGuid>eebba614-420c-49ed-ad36-739f402a02b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/div/div/div/div/div</value>
      <webElementGuid>a7524341-af54-4898-b587-0fe443ce2940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Favourites'])[1]/following::div[9]</value>
      <webElementGuid>fdb9bd5f-6333-4d78-846c-845b4a18f426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teams'])[1]/preceding::div[1]</value>
      <webElementGuid>a71a5b2e-c7db-43e6-9fcf-f39886db9d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sachin Tendular XI'])[1]/preceding::div[2]</value>
      <webElementGuid>892f5540-0ef7-4fcc-b26f-001a4c05f0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear']/parent::*</value>
      <webElementGuid>85ee0303-eb4c-4d5c-a43a-abd28cefe03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div</value>
      <webElementGuid>0ee598a9-6d0a-4ec8-95c4-d0c95b76b1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Clear' or . = 'Clear')]</value>
      <webElementGuid>8736aa9c-6d80-4bda-a060-4b8731a57f1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
