<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Favorites</name>
   <tag></tag>
   <elementGuidId>2f9885ae-c31b-419c-a79b-981418747c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.quicklinks__heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-container']/div/section/article/div/header/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Favorites&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f7e8cc7c-80ac-44ef-8dca-155f8ecad167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quicklinks__heading</value>
      <webElementGuid>84549580-7e40-408a-b4d6-8bc832fdddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>b1d7d4fb-d8aa-4593-91fb-e1907826cfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;main-content layout-dbc one-feed&quot;]/section[@class=&quot;col-one&quot;]/article[@class=&quot;sub-module quicklinks quicklinks--favorites&quot;]/div[@class=&quot;quicklinks__container&quot;]/header[@class=&quot;quicklinks__header&quot;]/h2[@class=&quot;quicklinks__heading&quot;]</value>
      <webElementGuid>36693922-0d6f-46a4-89b8-4f80fcd02e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-container']/div/section/article/div/header/h2</value>
      <webElementGuid>ac55eb2c-2fd2-4659-8607-d4de1cbe0cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cricket'])[14]/following::h2[1]</value>
      <webElementGuid>87cc0348-a07e-450f-94bf-cec0929d6e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cricket'])[13]/following::h2[1]</value>
      <webElementGuid>2a035ce5-7629-4aa7-bdd3-02cc5b9d4c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[2]/preceding::h2[1]</value>
      <webElementGuid>31d4d459-8c19-41ad-a510-c3df912e27d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRICKET'])[1]/preceding::h2[1]</value>
      <webElementGuid>8318eef1-a976-4fd9-83e3-0b01e5406e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Favorites']/parent::*</value>
      <webElementGuid>2bf1a06c-91f3-4ece-9abb-44c02608373e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/h2</value>
      <webElementGuid>3dcb5a1a-2de3-40b1-bbc1-74916cac275b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>2e511c14-caec-4854-8862-db7aa2ac72a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
