<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Favourites</name>
   <tag></tag>
   <elementGuidId>a2e7875e-69cd-40f1-9e29-f36623bc0418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.feed-title.favorites</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='global-header']/div[2]/ul/li[2]/div/div/ul[2]/li/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Favourites&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ad400b40-47d0-4a2d-ab46-00dc0ac83014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feed-title favorites</value>
      <webElementGuid>143e2533-f5ce-4245-be11-7cbfffb5e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favourites</value>
      <webElementGuid>99432962-c3b7-4a4a-9ad1-74c73c559748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[@class=&quot;container&quot;]/ul[@class=&quot;tools focused&quot;]/li[@class=&quot;user hover&quot;]/div[@class=&quot;global-user&quot;]/div[@class=&quot;global-user-container&quot;]/ul[@class=&quot;favs&quot;]/li[1]/div[@class=&quot;current-favorites&quot;]/h2[@class=&quot;feed-title favorites&quot;]</value>
      <webElementGuid>aaf5e0d5-c971-47aa-8c39-b7963987df40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='global-header']/div[2]/ul/li[2]/div/div/ul[2]/li/div/h2</value>
      <webElementGuid>5487ccdd-0a38-474c-afac-25de8639476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Settings'])[1]/following::h2[1]</value>
      <webElementGuid>d497171a-7fc3-44e9-9dd0-f7e83d08b354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome!'])[1]/following::h2[1]</value>
      <webElementGuid>1b29193f-8687-4960-89db-5c17067771f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Football'])[1]/preceding::h2[1]</value>
      <webElementGuid>b7139c36-699d-4ca3-9a85-30e45514b64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Football'])[2]/preceding::h2[1]</value>
      <webElementGuid>b8d1008e-c7ec-4017-9682-7b5d5e0d218a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Favourites']/parent::*</value>
      <webElementGuid>9017849d-56f0-404f-97dd-7d1f3cd13219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/h2</value>
      <webElementGuid>72fd2922-82c8-44f4-877b-3ff81989445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Favourites' or . = 'Favourites')]</value>
      <webElementGuid>0c2c87ee-3a1e-4495-8016-98142a9a9900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
