<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_cricket</name>
   <tag></tag>
   <elementGuidId>04ab2308-557d-4f99-980d-cd0492cd3589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.FavMgmt__Col.FavMgmt__Col--Right.flex.flex-column > div.FavMgmt__Wrapper.br2.flex-auto > ul.FavMgmt__Section > li.FavMgmt__Item.flex.items-center > div.FavMgmt__Details.flex.min-w-0.items-center.flex-grow > div.FavMgmt__Details__Txt.min-w-0.flex.flex-column.pl3 > h3.FavMgmt__Details__Cat.truncate.n10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section[2]/div/ul/li[2]/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;IndiacricketUnfollow&quot;i >> h3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>73061768-7723-4c25-88c7-1bf417216632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FavMgmt__Details__Cat truncate n10</value>
      <webElementGuid>ce266583-e7bd-4f6c-a1b8-6498b871afe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cricket</value>
      <webElementGuid>f17a93a8-91eb-4491-811e-30458ce444cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fittPortal_0&quot;)/div[@class=&quot;bp-mobile bp-mobileLG bp-mobileTablet bp-mobileMDPlus bp-mobileLGPlus no-touch&quot;]/div[@class=&quot;lightbox__wrapper flex justify-center lightbox__wrapper--mobile LightBox&quot;]/section[@class=&quot;lightbox__contentBox overflow-hidden relative lightbox__contentBox--heightWebkit lightbox__contentBox--mobile&quot;]/div[@class=&quot;lightbox__content lightbox__content--mobile&quot;]/div[@class=&quot;ResponsiveWrapper&quot;]/section[@class=&quot;Card FavMgmt FavMgmt--tabletPlus&quot;]/div[@class=&quot;Wrapper Card__Content&quot;]/section[@class=&quot;FavMgmt__Pane flex justify FavMgmt__Pane--searching&quot;]/section[@class=&quot;FavMgmt__Col FavMgmt__Col--Right flex flex-column&quot;]/div[@class=&quot;FavMgmt__Wrapper br2 flex-auto&quot;]/ul[@class=&quot;FavMgmt__Section&quot;]/li[@class=&quot;FavMgmt__Item flex items-center&quot;]/div[@class=&quot;FavMgmt__Details flex min-w-0 items-center flex-grow&quot;]/div[@class=&quot;FavMgmt__Details__Txt min-w-0 flex flex-column pl3&quot;]/h3[@class=&quot;FavMgmt__Details__Cat truncate n10&quot;]</value>
      <webElementGuid>9235d6fb-de86-4b62-ab43-2693dab48634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , favorites-manager-ifra_846b91</value>
      <webElementGuid>81906afa-f0bf-484d-bd12-377bf1ffd123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section[2]/div/ul/li[2]/div/div[2]/h3</value>
      <webElementGuid>d343d241-87ad-4817-a3b3-6fb40b95955f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::h3[1]</value>
      <webElementGuid>9409881b-1ccc-4696-837b-e95ba42911b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Teams'])[1]/following::h3[1]</value>
      <webElementGuid>dd925e96-06d5-4d3c-b712-143e2485ec8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unfollow'])[2]/preceding::h3[1]</value>
      <webElementGuid>9921451c-9579-4a23-8dd6-62cf9f5edc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mumbai Indians'])[1]/preceding::h3[1]</value>
      <webElementGuid>b68dd1ff-ba82-47ae-a454-36a6975bf2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/ul/li[2]/div/div[2]/h3</value>
      <webElementGuid>4c10d60b-8ebd-4837-9470-0f8a1575b2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'cricket' or . = 'cricket')]</value>
      <webElementGuid>d1d4d907-caa9-442e-8319-efd5ce00726c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
