<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_cricket_1_2</name>
   <tag></tag>
   <elementGuidId>41f5d356-9ca2-40bb-bdd7-00fbc7bbf650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section[2]/div/ul/li[4]/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>ul >> internal:has-text=&quot;My TeamsIndiacricketUnfollowMumbai IndianscricketUnfollowChennai Super Kingscric&quot;i >> h3 >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>2dcba040-04ba-4520-94a2-a7fe832ededd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FavMgmt__Details__Cat truncate n10</value>
      <webElementGuid>e48d02d1-f309-483f-8b4b-1737a5f8674b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cricket</value>
      <webElementGuid>461fee1a-ffe7-4adc-a9df-59cbca1d16d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fittPortal_0&quot;)/div[@class=&quot;bp-mobile bp-mobileLG bp-mobileTablet bp-mobileMDPlus bp-mobileLGPlus no-touch&quot;]/div[@class=&quot;lightbox__wrapper flex justify-center lightbox__wrapper--mobile LightBox&quot;]/section[@class=&quot;lightbox__contentBox overflow-hidden relative lightbox__contentBox--heightWebkit lightbox__contentBox--mobile&quot;]/div[@class=&quot;lightbox__content lightbox__content--mobile&quot;]/div[@class=&quot;ResponsiveWrapper&quot;]/section[@class=&quot;Card FavMgmt FavMgmt--tabletPlus&quot;]/div[@class=&quot;Wrapper Card__Content&quot;]/section[@class=&quot;FavMgmt__Pane flex justify FavMgmt__Pane--searching&quot;]/section[@class=&quot;FavMgmt__Col FavMgmt__Col--Right flex flex-column&quot;]/div[@class=&quot;FavMgmt__Wrapper br2 flex-auto&quot;]/ul[@class=&quot;FavMgmt__Section&quot;]/li[@class=&quot;FavMgmt__Item flex items-center&quot;]/div[@class=&quot;FavMgmt__Details flex min-w-0 items-center flex-grow&quot;]/div[@class=&quot;FavMgmt__Details__Txt min-w-0 flex flex-column pl3&quot;]/h3[@class=&quot;FavMgmt__Details__Cat truncate n10&quot;]</value>
      <webElementGuid>b9618402-93a2-4902-9b17-aad3e9424e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , favorites-manager-ifra_846b91</value>
      <webElementGuid>d9672163-a772-4057-9511-60c6a5c47335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/section[2]/div/ul/li[4]/div/div[2]/h3</value>
      <webElementGuid>9f7b5ff5-09f6-45ec-ad92-cc9dcffadfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai Super Kings'])[2]/following::h3[1]</value>
      <webElementGuid>3776da7f-b644-492b-82cf-1ec997f006ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unfollow'])[3]/following::h3[1]</value>
      <webElementGuid>e7176ce2-d672-4ba1-81db-7aebc730b027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unfollow'])[4]/preceding::h3[1]</value>
      <webElementGuid>e8dfc060-bdab-442f-9de2-058737bceb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Players'])[1]/preceding::h3[1]</value>
      <webElementGuid>40a73f8e-d5a1-4204-905d-8b0f179950c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/ul/li[4]/div/div[2]/h3</value>
      <webElementGuid>8262851d-938a-459f-839f-71ccd4c79b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'cricket' or . = 'cricket')]</value>
      <webElementGuid>d9e2b793-0248-41d4-a7b7-7ecfff1aad5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
