<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</name>
   <tag></tag>
   <elementGuidId>71f70345-fb74-4d6b-b0f9-aed08a1da85d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oneid-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='oneid-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;oneid-iframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>23a1764f-ae8e-4b63-bb07-a330953664ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>a0a539fa-542d-4ea3-81ef-e76bc27eeaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>641efc8e-f6b0-4bd9-8656-5840dcbdd726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd40058f-dc18-4bec-ae46-7915a8498a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>5ea2f112-31b2-4cf6-b229-5cd93983e090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-IN?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcorev4.css&amp;logLevel=INFO</value>
      <webElementGuid>44e2eafa-46a6-4f8b-822a-888715930a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneid-iframe&quot;)</value>
      <webElementGuid>46c5f59f-0925-4e94-8a54-f1c1254a0c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='oneid-iframe']</value>
      <webElementGuid>e6a5ea8a-e884-4832-894a-17ea4ef9df55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oneid-wrapper']/iframe</value>
      <webElementGuid>2e342795-178e-41b1-8b68-b505b414580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>11f10dde-8c4e-4448-a32a-8251b6d63f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'oneid-iframe' and @name = 'oneid-iframe' and @title = 'Account' and @src = 'https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-IN?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcorev4.css&amp;logLevel=INFO']</value>
      <webElementGuid>fd6b0ee4-1841-49fd-a700-6a646d419043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
