<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , google_ads_iframe_2178_d3fc42</name>
   <tag></tag>
   <elementGuidId>9b0a764f-1452-4fd2-941e-d8fbff94307c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oneid-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='oneid-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;oneid-iframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4fd85d32-c559-435f-9e1e-6a2ac42503d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>f469c4fc-30ad-4ed7-8160-2af636de7ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oneid-iframe</value>
      <webElementGuid>38d83015-0004-4c5e-ae8e-82a417988dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>efc5b3be-fdd2-40cf-89fd-5c86c9364ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>c8555c1d-9c65-4212-aad5-2940b64681d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-IN?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcorev4.css&amp;logLevel=INFO</value>
      <webElementGuid>622908b8-e8c9-41ec-b9bf-35b998b8f995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneid-iframe&quot;)</value>
      <webElementGuid>8a7b5a03-8c55-474c-8503-f01b6d447207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='oneid-iframe']</value>
      <webElementGuid>d4bac81c-dbaa-4041-89cf-0580630ff192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='oneid-wrapper']/iframe</value>
      <webElementGuid>0fa0721d-f52f-42f1-a4a6-63b21d98eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>760a93bb-4704-4dbf-aebb-5d1b5a93c1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'oneid-iframe' and @name = 'oneid-iframe' and @title = 'Account' and @src = 'https://cdn.registerdisney.go.com/v4/bundle/web/ESPN-ONESITE.WEB/en-IN?cssOverride=https%3A%2F%2Fsecure.espncdn.com%2Fcombiner%2Fc%3Fcss%3Ddisneyid%2Fcorev4.css&amp;logLevel=INFO']</value>
      <webElementGuid>4ac04ab8-509a-4895-8440-499f8d2ee844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
