<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , favorites-manager-ifra_846b91</name>
   <tag></tag>
   <elementGuidId>4ce88abc-8b90-41d7-91e6-1e7b8a45a9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#favorites-manager-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='favorites-manager-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#favorites-manager-iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2762dd69-eb96-4e85-9521-4e328a980fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.espn.in/preferences?platform=iframe&amp;parentDomain=https%3A%2F%2Fwww.espn.in&amp;layout=desktop&amp;lang=en&amp;region=in&amp;site=espn&amp;section=frontpage</value>
      <webElementGuid>5223de12-5b1a-4d51-a1f5-fbe2760d6482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e39aba48-0bfc-4b5f-9a76-2105358439b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>favorites-manager-iframe</value>
      <webElementGuid>cab846dc-248b-4371-8bdf-bd85e91c5d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b5260c8c-0469-42de-8f95-7e2023915dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;favorites-manager-iframe&quot;)</value>
      <webElementGuid>30dd2cd8-9288-4081-95ee-bc13a556dd64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='favorites-manager-iframe']</value>
      <webElementGuid>809bfb25-1f51-4496-90e8-90d33adf38e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/iframe</value>
      <webElementGuid>19678ef7-cc7d-4908-9fa7-7339a6215701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.espn.in/preferences?platform=iframe&amp;parentDomain=https%3A%2F%2Fwww.espn.in&amp;layout=desktop&amp;lang=en&amp;region=in&amp;site=espn&amp;section=frontpage' and @id = 'favorites-manager-iframe']</value>
      <webElementGuid>72e1ed51-1b98-4a7e-9cb9-58508ca1b3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
