<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Favourites_FavMgmt__Pane__Search__Input</name>
   <tag></tag>
   <elementGuidId>64366c28-db7b-422a-8d81-e00235da7938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FavMgmt__Pane__Search__Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FavMgmt__Pane__Search__Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search for teams, players, and leagues&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e8cb70c-2d26-4ba4-bc03-0855447ad1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TypeaheadInput TypeaheadInput--Controls TypeaheadInput--Controls-Single form__control</value>
      <webElementGuid>ce5f8dbf-3e9d-4ac3-b19e-0167b74cf528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FavMgmt__Pane__Search__Input</value>
      <webElementGuid>ea323d94-b7f1-49da-9971-9a3f530b66d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for teams, players, and leagues</value>
      <webElementGuid>f16c448c-ba15-46f8-9c9d-f7022db41d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a22eb668-c433-4686-9d44-c13ef9123ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FavMgmt__Pane__Search__Input&quot;)</value>
      <webElementGuid>f2780049-0290-40e4-91b9-1ecd833567da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , favorites-manager-ifra_846b91</value>
      <webElementGuid>c37ea1f3-293a-45d8-8635-0ab830935f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FavMgmt__Pane__Search__Input']</value>
      <webElementGuid>ad3ac13c-a6a3-477c-bc71-c39e00a0851b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fittPortal_0']/div/div/section/div/div/section/div/section/div/div/div/input</value>
      <webElementGuid>f123726d-02f4-43ad-aeae-46c4fde6e5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e650d6d5-3ca6-45e2-8dcc-e8ff3b063501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FavMgmt__Pane__Search__Input' and @placeholder = 'Search for teams, players, and leagues' and @type = 'search']</value>
      <webElementGuid>7d01319f-42b3-46cc-acbd-cf0ff64f3bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
