<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Avoid using the same password from an_70fa4b</name>
   <tag></tag>
   <elementGuidId>89f55a41-55c4-4b87-9647-1e9970a3175a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;BU_\*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ae98f59-958b-4577-b72b-4de8b9618da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fdadf2d-d9e9-46fe-93e5-be12636f5295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Yes! I would like to receive occasional information and offers about my favorite teams, sports and other information from ESPN, ESPN+ and The Walt Disney Family of Companies</value>
      <webElementGuid>443b1bcb-35c2-4869-a56c-d0b2c1e011ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7bf4d19-c02a-4113-9fd7-cde66a74eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a44d70e5-a2b9-43b4-a073-0207a15e50b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b</value>
      <webElementGuid>9851aa66-6317-406b-8051-ac0d709e52a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b</value>
      <webElementGuid>7d4af182-5127-488c-a040-c2a06f7b9a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb1acc62-c790-4bfe-b5e0-696d7a1959fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4e946b16-5d82-48c9-812c-5185bc1f9a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b&quot;)</value>
      <webElementGuid>db6111bc-ec57-4f99-9299-7703da388451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>e4b46b5b-d017-421e-8410-49e1edeaeca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b']</value>
      <webElementGuid>ddeb8569-d78a-40bd-bbb0-f004470f8a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div/div/form/label/input</value>
      <webElementGuid>48c679c7-0b16-48ae-ac3f-8d0c0265daed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>83b45ff0-9d85-4a70-8861-6bcf32d33be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BU_*_LOCATION_DE_bloc__8e148cb1b0cfd8814531604752220a7b' and @type = 'checkbox']</value>
      <webElementGuid>a479bdfc-b5d5-4e33-ab12-f0457d48441e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
