<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_By creating an account, I agree to the Te_2b39dd</name>
   <tag></tag>
   <elementGuidId>ab4f9193-8c31-497c-b5cf-a184aed72889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gtou_ppv2_proxy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='gtou_ppv2_proxy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;gtou_ppv2_proxy&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>94342a0b-ea76-4846-9423-4d96248c7fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-block legal small</value>
      <webElementGuid>17638aa8-752a-4559-9d80-322d9c6f1f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gtou_ppv2_proxy</value>
      <webElementGuid>f1d503ed-9d0f-4f42-bf43-045347563c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>gtou_ppv2_proxy</value>
      <webElementGuid>d4a1f5aa-6790-4a48-8c7f-66bafd245246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By creating an account, I agree to the Terms of Use and acknowledge that I have read the Privacy Policy.</value>
      <webElementGuid>9effd5c2-27ea-474e-8578-99f146f5c796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gtou_ppv2_proxy&quot;)</value>
      <webElementGuid>5d306477-1798-4984-b2bd-5ff79527e022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>05f6af5f-09cc-45a1-a36b-e5ee17ef5284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='gtou_ppv2_proxy']</value>
      <webElementGuid>6ef1c70a-68f8-4ddd-91a2-e85e3042cf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div/div/form/p[2]</value>
      <webElementGuid>0f90e5d2-e460-4dfc-ad20-a6a187ced466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avoid using the same password from another account.'])[1]/following::p[2]</value>
      <webElementGuid>7aa1ae10-ae9b-4ffd-921f-a0aff9706204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use letters with at least one number or special character'])[1]/following::p[2]</value>
      <webElementGuid>5a0ad6e3-21dd-41a3-9f18-acd1296ab1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='By creating an account, I agree to the']/parent::*</value>
      <webElementGuid>6a426926-01ae-4c49-99c0-026c5564628a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>3be596f5-2477-428d-901c-370ff8ad6225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'gtou_ppv2_proxy' and (text() = 'By creating an account, I agree to the Terms of Use and acknowledge that I have read the Privacy Policy.' or . = 'By creating an account, I agree to the Terms of Use and acknowledge that I have read the Privacy Policy.')]</value>
      <webElementGuid>048a9142-efce-4eff-b6ec-79ec981e36d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
