<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_With a MyDisney account, you can log into_de2eed</name>
   <tag></tag>
   <elementGuidId>ba1f2ee9-a893-4215-bb60-508a0374d2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdentityRegisterSubHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='IdentityRegisterSubHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;IdentityRegisterSubHeading&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>791d8821-b0f4-4978-9521-636cf74817ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-block text-left identity-flow is-description-text description</value>
      <webElementGuid>ed87d277-fe3c-41f1-9cf7-3adbef3f9683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdentityRegisterSubHeading</value>
      <webElementGuid>f944ffdd-8eca-4dd8-860d-c56b4f30e83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>IdentityRegisterSubHeading</value>
      <webElementGuid>d0db867c-91d2-4cdd-8ee4-436d91258c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>With a MyDisney account, you can log into ESPN and other services across The Walt Disney Family of Companies. Create your account using kat@psl.com edit</value>
      <webElementGuid>19b0b594-17f7-425c-a3b4-c0f8c520b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdentityRegisterSubHeading&quot;)</value>
      <webElementGuid>fb30480f-4b97-48d2-be36-d66fb8ea480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>921f2e02-cec2-4915-a012-8c290f9e5341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='IdentityRegisterSubHeading']</value>
      <webElementGuid>063d72f2-eb1d-4eba-b468-768670f136a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div/div/form/p</value>
      <webElementGuid>603c587c-c2f5-4760-a267-cce9390d8793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account to continue'])[1]/following::p[1]</value>
      <webElementGuid>26ce4059-e25d-46fc-96cf-5bbeace257ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a minimum of six characters (case sensitive)'])[1]/preceding::p[1]</value>
      <webElementGuid>c50be2ef-2bf1-452a-9c00-14933b84534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='With a MyDisney account, you can log into ESPN and other services across The Walt Disney Family of Companies. Create your account using']/parent::*</value>
      <webElementGuid>4dd65b9c-ed32-4e57-8924-42a635b78d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>3a582f07-aa14-4d27-a65c-7579e625f40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'IdentityRegisterSubHeading' and (text() = 'With a MyDisney account, you can log into ESPN and other services across The Walt Disney Family of Companies. Create your account using kat@psl.com edit' or . = 'With a MyDisney account, you can log into ESPN and other services across The Walt Disney Family of Companies. Create your account using kat@psl.com edit')]</value>
      <webElementGuid>4d13eb1d-eeb5-4639-a205-862bd4021c28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
