<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter a password</name>
   <tag></tag>
   <elementGuidId>94767622-f09f-4edf-848a-be91199d2f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-new-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password-new-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;password-new-error&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a7b4f8d-62e0-4574-bf63-1ef543f64414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-error input-error-password input-error-password-new displayed</value>
      <webElementGuid>34d67770-74f8-4d94-9075-921b2ca3fe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-new-error</value>
      <webElementGuid>012d8c7e-0546-4b74-a8ab-d62193f4684b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>password-new-error</value>
      <webElementGuid>d3d3a528-2477-4cf4-9a3e-d7faa2b2da2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>5bce62ea-a0fb-48ef-a903-7f80415c7ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a password.</value>
      <webElementGuid>b6c8a535-35fa-4dde-ba8e-e2db95c51ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-new-error&quot;)</value>
      <webElementGuid>31e2cf0e-7b28-41ab-b89b-8fd116ffb15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>f9a145b4-d8cd-4648-90b1-580f8b9a1ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password-new-error']</value>
      <webElementGuid>ffc3aae7-e423-4107-af65-fcbe97f434a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasswordPanel']/div/div[2]/span</value>
      <webElementGuid>5144ab30-e850-49b3-bd51-1ee6722a339b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your surname.'])[1]/following::span[1]</value>
      <webElementGuid>ae4ac332-3b0a-48ef-9cac-5974580ef427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your first name.'])[1]/following::span[2]</value>
      <webElementGuid>4cc7ba39-375c-4b4a-9b66-31b20fdfe953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a minimum of six characters (case sensitive)'])[1]/preceding::span[2]</value>
      <webElementGuid>fdf2558b-3ab1-4842-a71d-b23f828c44f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use letters with at least one number or special character'])[1]/preceding::span[2]</value>
      <webElementGuid>1b12356f-bb43-438d-ace8-34b6178b1657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a password.']/parent::*</value>
      <webElementGuid>7d3d41e1-eebf-4533-8e5b-2966e0b4dbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span</value>
      <webElementGuid>e655ff54-696d-444e-bee8-2f73280189cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password-new-error' and (text() = 'Please enter a password.' or . = 'Please enter a password.')]</value>
      <webElementGuid>50d75f15-9054-45a1-bdf0-17ecdb8a5bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
