<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_This email address isnt correctly form_809224</name>
   <tag></tag>
   <elementGuidId>e3c0d4d4-c818-4b46-a147-26837efe669c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputIdentityFlowValue-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='InputIdentityFlowValue-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;InputIdentityFlowValue-error&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a7d3440-3f7e-4501-9fe1-0042892b57b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-error input-error-email input-error-InputIdentityFlowValue displayed</value>
      <webElementGuid>6fcec04f-00c5-4607-85ef-7874bc4c1e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputIdentityFlowValue-error</value>
      <webElementGuid>b3938d21-2530-4213-8c11-945486a7aef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>InputIdentityFlowValue-error</value>
      <webElementGuid>de5a1860-4365-4aa8-854f-5d787b1b8593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>bd100f44-4a79-4771-9907-4d0e98346745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This email address isn’t correctly formatted. Try again?</value>
      <webElementGuid>1b15e439-eb28-47b1-bbcd-905d6a978c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputIdentityFlowValue-error&quot;)</value>
      <webElementGuid>22c16934-7d6b-41a8-b4a8-9f8b3676f83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>fb28e745-13aa-41fd-937d-1de012ac9a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='InputIdentityFlowValue-error']</value>
      <webElementGuid>114559ff-c972-4816-ad6b-8b33c2b1040a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[2]/div/div/form/div[2]/div[2]/span</value>
      <webElementGuid>75c07a18-e722-4f96-a6fb-13d937b39cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your email address to continue'])[1]/following::span[1]</value>
      <webElementGuid>0235ba85-7162-4cc5-b029-4e8e71de1a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPN is part of The Walt Disney Family of Companies.'])[1]/preceding::span[1]</value>
      <webElementGuid>2640c2bb-a95b-4e3b-8df3-1190ca46bac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This email address isn’t correctly formatted. Try again?']/parent::*</value>
      <webElementGuid>7ec86b2f-1936-4e9b-af1e-479df143ce8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>22419ab2-e3bd-41f7-8ea9-1efc832008b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'InputIdentityFlowValue-error' and (text() = 'This email address isn’t correctly formatted. Try again?' or . = 'This email address isn’t correctly formatted. Try again?')]</value>
      <webElementGuid>aaa4de34-e594-4213-ba30-e31b4c784550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
