<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_katpsl.com</name>
   <tag></tag>
   <elementGuidId>7764fd1b-3919-4956-b57d-cf9f3f79631e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IDFlowLoginValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='IDFlowLoginValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;kat@psl.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2edd4ed-7dd4-4871-8305-b88050e3ff24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IDFlowLoginValue</value>
      <webElementGuid>8338878a-881d-4d30-80b7-92465fb083eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kat@psl.com</value>
      <webElementGuid>7d2b34a9-f482-4054-ae40-6e3fe6e260fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IDFlowLoginValue&quot;)</value>
      <webElementGuid>d0816a25-ad31-4b36-b4df-ddcb171d2075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>2c463792-ce29-4780-ae4a-7fa68a50d71f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='IDFlowLoginValue']</value>
      <webElementGuid>5acd9083-12da-4cff-9876-8cef98c81dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='IdentityRegisterSubHeading']/span</value>
      <webElementGuid>508c7e5b-85b5-4470-8129-758bcfeb2536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account to continue'])[1]/following::span[1]</value>
      <webElementGuid>c92beb15-f5f3-4832-99f1-152b13709f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a minimum of six characters (case sensitive)'])[1]/preceding::span[3]</value>
      <webElementGuid>e68b21c1-5d21-4f50-ac9c-4a5b898a9164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use letters with at least one number or special character'])[1]/preceding::span[3]</value>
      <webElementGuid>dd0c2de1-4265-45a3-856b-369b909659c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kat@psl.com']/parent::*</value>
      <webElementGuid>88bb98c4-ffd6-40bc-a7af-4eae5aaa8608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>1c0440fc-deab-4077-a11d-0ef08b6a837a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'IDFlowLoginValue' and (text() = 'kat@psl.com' or . = 'kat@psl.com')]</value>
      <webElementGuid>0ab3e22d-4596-4581-8d8c-c73a31484666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
