<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please make sure your password is at l_41d89e</name>
   <tag></tag>
   <elementGuidId>84c8d563-b3ca-417f-96ee-63d0b400ec05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-new-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='password-new-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;password-new-error&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>381e42d6-6eaa-476f-af74-a00df2ee1dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-error input-error-password input-error-password-new displayed</value>
      <webElementGuid>6c5ea9ec-9819-4e32-bd21-58ccfcbc6a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-new-error</value>
      <webElementGuid>860a9e3f-a614-41ba-a9c6-b3e23f0cd4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>password-new-error</value>
      <webElementGuid>0f4f0802-8027-4661-8a19-a6e968e48b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>3211e4dd-9083-4cea-b74b-431077be97cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please make sure your password is at least six characters, includes at least one number or special character, and is not a commonly used password.</value>
      <webElementGuid>a87f25ad-6fc7-4b47-9fcc-4e2e1ca8ff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-new-error&quot;)</value>
      <webElementGuid>4a44eb51-f1bc-4dd3-9ef9-330645f51f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPN/Page_ESPN India - Serving Sports Fans. Anyt_cfbf67/iframe_concat(id(, , oneid-iframe, , ))_one_8d9a57</value>
      <webElementGuid>d093044e-1b6b-49fd-a0b8-7c4be2ab4b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='password-new-error']</value>
      <webElementGuid>99d228eb-a210-45cc-8dbe-382d7d2a7283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PasswordPanel']/div/div[2]/span</value>
      <webElementGuid>9296d892-1f1f-4721-993b-f37989bba848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kat@psl.com'])[1]/following::span[1]</value>
      <webElementGuid>ae8417e4-fdb4-4ec2-a3b0-9c02ec36c56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account to continue'])[1]/following::span[2]</value>
      <webElementGuid>a93303ec-2992-47af-9450-96ee2297406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a minimum of six characters (case sensitive)'])[1]/preceding::span[2]</value>
      <webElementGuid>dbed958b-d2f0-45bd-8d5f-8cf540bbd373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use letters with at least one number or special character'])[1]/preceding::span[2]</value>
      <webElementGuid>0ae5f4e2-4a33-4c86-b891-f9cf6c30e2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please make sure your password is at least six characters, includes at least one number or special character, and is not a commonly used password.']/parent::*</value>
      <webElementGuid>489ac2eb-dd5b-40e6-82b9-be702e2aa970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>72b6125c-cf89-48c2-99fe-7e28677c14e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'password-new-error' and (text() = 'Please make sure your password is at least six characters, includes at least one number or special character, and is not a commonly used password.' or . = 'Please make sure your password is at least six characters, includes at least one number or special character, and is not a commonly used password.')]</value>
      <webElementGuid>5225f22f-e7fc-4f4b-b902-df496b60b6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swan@abc.com'])[1]/following::span[1]</value>
      <webElementGuid>3890a99d-3e53-4378-9065-cd2d68957675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
