<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_India</name>
   <tag></tag>
   <elementGuidId>6dedf8e1-3de2-4a10-b0b8-1f4cb7a34284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.quicklinks_list__name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='favfeed-quicklinks']/li/a/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;India CRICKET&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15ba9ccc-e0a0-412e-8cc2-391750a6251b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quicklinks_list__name</value>
      <webElementGuid>f1124983-7965-4c50-babd-7821c68e03f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>6daaa9d7-1bd3-4726-8518-44c08168dea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;favfeed-quicklinks&quot;)/li[@class=&quot;quicklinks_list__item favItem--pregame type-game featured&quot;]/a[@class=&quot;quicklinks_list__link&quot;]/div[@class=&quot;quicklinks_list__detail&quot;]/span[@class=&quot;quicklinks_list__name&quot;]</value>
      <webElementGuid>77f8b40b-70f2-4ae3-bfc9-aa1b2ad4528e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='favfeed-quicklinks']/li/a/div[2]/span</value>
      <webElementGuid>335b9037-0cb0-45e4-8703-839e4d698260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites'])[1]/following::span[1]</value>
      <webElementGuid>45bd97da-9060-4c5d-9dfb-9c215c18c83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cricket'])[14]/following::span[1]</value>
      <webElementGuid>6829f2fc-0c23-44af-ad9c-387f3ccd770c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRICKET'])[1]/preceding::span[1]</value>
      <webElementGuid>ed56b2fd-4712-44b2-8404-fdcae8566400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSK'])[1]/preceding::span[2]</value>
      <webElementGuid>00080143-4306-414f-a0b2-3304e4a01b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/ul/li/a/div[2]/span</value>
      <webElementGuid>aeb19e7c-0bac-47c4-ad4d-a10531431ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'India' or . = 'India')]</value>
      <webElementGuid>d6866cdd-6b46-4062-b892-89778071701c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
