<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-dashboard_AutomationAutomation Practice_d70d87</name>
   <tag></tag>
   <elementGuidId>cbb089ba-7d51-40e3-9033-a3809e5352e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-dashboard.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AutomationAutomation Practice HOME ORDERS Cart 3 Sign Out Filters Home | SearchF&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-dashboard</value>
      <webElementGuid>cc14f222-7ee7-49c1-bda3-e54628726287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>2c9fcba7-94b6-4589-9a32-92ab0e55d9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutomationAutomation Practice HOME            ORDERS  Cart 3 Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 2 results   |  User can only see maximum 9 products on a pageZARA COAT 3$ 31500 View Add To CartADIDAS ORIGINAL$ 31500 View Add To Cart Previous page 1 / 1 You're on page 1 Next pageDesign and Developed By - Kunal Sharma</value>
      <webElementGuid>b7b3f6a1-93f6-41cc-b90f-379bb878ab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>588a4832-78ae-41a9-85be-0e5815ffd01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dashboard</value>
      <webElementGuid>09eaae8b-1546-4408-9003-e0304052d3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-dashboard[(text() = concat(&quot;AutomationAutomation Practice HOME            ORDERS  Cart 3 Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 2 results   |  User can only see maximum 9 products on a pageZARA COAT 3$ 31500 View Add To CartADIDAS ORIGINAL$ 31500 View Add To Cart Previous page 1 / 1 You&quot; , &quot;'&quot; , &quot;re on page 1 Next pageDesign and Developed By - Kunal Sharma&quot;) or . = concat(&quot;AutomationAutomation Practice HOME            ORDERS  Cart 3 Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 2 results   |  User can only see maximum 9 products on a pageZARA COAT 3$ 31500 View Add To CartADIDAS ORIGINAL$ 31500 View Add To Cart Previous page 1 / 1 You&quot; , &quot;'&quot; , &quot;re on page 1 Next pageDesign and Developed By - Kunal Sharma&quot;))]</value>
      <webElementGuid>cf76faea-263d-4a08-87d9-5aa849b6f94b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
