<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-dashboard_AutomationAutomation Practice_538625</name>
   <tag></tag>
   <elementGuidId>bb9e3480-47ea-45cc-ad3e-5cc3219fe330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-dashboard.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AutomationAutomation Practice HOME ORDERS Cart Sign Out Filters Home | SearchFil&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-dashboard</value>
      <webElementGuid>8cffa2ae-1a20-4b9f-ac58-80adc007ab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>af661a2a-ed93-4132-9ab2-d3d2918db470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutomationAutomation Practice HOME            ORDERS  Cart  Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 0 results   |  User can only see maximum 9 products on a page Previous page 1 / 1 You're on page 1 Next pageDesign and Developed By - Kunal Sharma</value>
      <webElementGuid>f7728f76-780e-41b3-be93-9081fb789c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>589a1eeb-9f7f-4417-b12c-423b0e9f8efa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dashboard</value>
      <webElementGuid>7ed33a95-bc3b-41e7-9725-ead8261a5bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-dashboard[(text() = concat(&quot;AutomationAutomation Practice HOME            ORDERS  Cart  Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 0 results   |  User can only see maximum 9 products on a page Previous page 1 / 1 You&quot; , &quot;'&quot; , &quot;re on page 1 Next pageDesign and Developed By - Kunal Sharma&quot;) or . = concat(&quot;AutomationAutomation Practice HOME            ORDERS  Cart  Sign Out Filters Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch FormenwomenShowing 0 results   |  User can only see maximum 9 products on a page Previous page 1 / 1 You&quot; , &quot;'&quot; , &quot;re on page 1 Next pageDesign and Developed By - Kunal Sharma&quot;))]</value>
      <webElementGuid>3199c045-c45e-4f2f-a109-1690960c68cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
