<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IPHONE 13 PRO</name>
   <tag></tag>
   <elementGuidId>7ffd857a-6b86-4629-818f-b8339661b885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='htmlData']/tbody/tr[6]/td/table/tbody/div/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;IPHONE 13 PRO&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c29dadef-1d46-42c9-9d4e-0e775dfaeab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>de28a0ac-3839-4450-80dc-0abc910c3d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IPHONE 13 PRO</value>
      <webElementGuid>13a2ffe0-e36c-4ba7-90ba-31779923f4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;htmlData&quot;)/tbody[1]/tr[6]/td[@class=&quot;box box-ext order-summary-box&quot;]/table[@class=&quot;order-summary&quot;]/tbody[1]/div[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;line-item ng-star-inserted&quot;]/td[@class=&quot;line-item product-info-column m-3&quot;]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>325ba84d-ad2c-45b6-af72-095df15a3eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='htmlData']/tbody/tr[6]/td/table/tbody/div/tr/td[2]/div</value>
      <webElementGuid>8c71147f-77f1-4372-b084-34f7c5a52058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| 67ba1debc019fb1ad6074437 |'])[1]/following::div[2]</value>
      <webElementGuid>75159e36-aae8-4a22-80a7-d90716a1a60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders History Page'])[1]/following::div[2]</value>
      <webElementGuid>3a480409-f688-45dc-b3ff-64219ff7271f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty: 1'])[1]/preceding::div[1]</value>
      <webElementGuid>7532eed0-d602-4fff-a1cc-e6d3814de33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 231500'])[1]/preceding::div[2]</value>
      <webElementGuid>4a8f5ca5-8775-401b-9f92-ba5519b1ab66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IPHONE 13 PRO']/parent::*</value>
      <webElementGuid>9ea40020-ec1d-4ee0-901b-6bf1bac9861f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>e82a6ec8-d836-4fe7-b177-257fa123b2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'IPHONE 13 PRO' or . = 'IPHONE 13 PRO')]</value>
      <webElementGuid>8fb21149-c29f-49de-9d78-b28304f431a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
