<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Buy Now_fa fa-trash-o</name>
   <tag></tag>
   <elementGuidId>2f2e486b-87e1-47d8-bc16-e8806738948d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;❯&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bac2ffce-2550-4302-af8f-60a7bf9901aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53edadd7-02b5-4544-9801-4bfa52744d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash-o</value>
      <webElementGuid>c3b58a5c-66ce-43fa-8743-53b6851ef5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-profile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrap cf&quot;]/div[@class=&quot;cart&quot;]/ul[@class=&quot;cartWrap ng-star-inserted&quot;]/li[@class=&quot;items even ng-star-inserted&quot;]/div[@class=&quot;infoWrap&quot;]/div[@class=&quot;cartSection removeWrap&quot;]/button[@class=&quot;btn btn-danger&quot;]/i[@class=&quot;fa fa-trash-o&quot;]</value>
      <webElementGuid>be581338-2f98-44b1-a431-77e7e276c61c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>4c320721-1436-4f35-839a-9f7b67c39b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
