<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>e2877df4-ca6f-4566-b80a-24658be10cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebar > form.ng-untouched.ng-pristine.ng-valid > div.py-2.border-bottom.ml-3 > div.form-group.ng-star-inserted > input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sidebar div >> internal:has-text=/^fashion$/ >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d7d787b-c008-4b3b-a17b-9e4ac13e8195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55c31bea-11b4-4dc1-b55f-4b1556b1ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;py-2 border-bottom ml-3&quot;]/div[@class=&quot;form-group ng-star-inserted&quot;]/input[1]</value>
      <webElementGuid>9f4a206b-aaec-43e5-8314-5d020a431e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[12]</value>
      <webElementGuid>1611f30a-1ff4-47f9-b53a-8abb46dbdb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sidebar']/form/div[3]/div[2]/input</value>
      <webElementGuid>81d27407-a08a-493a-bedc-556ca17ad29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/form/div[3]/div[2]/input</value>
      <webElementGuid>7e782a44-e919-4b67-bbcc-02ad0c28c917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>27637264-5fc9-4e1c-a8d2-fc4db4429ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[16]</value>
      <webElementGuid>2d2f04ef-c80f-4f30-b593-6c9a486c44b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='sidebar']/form/div[4]/div[3]/input</value>
      <webElementGuid>df063b71-92a8-40c7-a7c2-cf847da961c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/form/div[4]/div[3]/input</value>
      <webElementGuid>af093db0-4ebc-4e83-b2c5-5dddebcc0258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
