<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Orders History Page</name>
   <tag></tag>
   <elementGuidId>c198b1d2-97a8-4848-8a51-1febb150a5cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.em-spacer-1 > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='htmlData']/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr[2]/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Orders History Page&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63140d17-b5d0-4fb9-86c5-82f7efb0e886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/dashboard/myorders</value>
      <webElementGuid>d2c9622f-5f66-4c41-af47-1ed626886d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a798c58e-827e-4a2a-8bbc-67b911c14011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Orders History Page </value>
      <webElementGuid>8edf04a5-f9d9-4689-98ee-c97d7b5eafd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;htmlData&quot;)/tbody[1]/tr[4]/td[@class=&quot;box&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[@class=&quot;em-spacer-1&quot;]/label[1]</value>
      <webElementGuid>f177ce47-4b38-447a-a83e-f5f100092c74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='htmlData']/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr[2]/td/label</value>
      <webElementGuid>fdc48362-b246-48d3-b4f1-71d8925615b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thankyou for the order.'])[1]/following::label[1]</value>
      <webElementGuid>a60d0ce8-101f-47ee-a27a-77570dc3eebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| 67b7671ec019fb1ad603c006 |'])[1]/preceding::label[1]</value>
      <webElementGuid>526be1ab-d2b9-4dbd-a4b8-afc0a573f082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPHONE 13 PRO'])[1]/preceding::label[2]</value>
      <webElementGuid>69d579ce-c2b2-4694-8584-1bd8e601c030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orders History Page']/parent::*</value>
      <webElementGuid>75d6e8a0-1a8a-4740-88cb-465dbcc230e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label</value>
      <webElementGuid>168a5b4a-c266-495b-b6d0-2c0439f8787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Orders History Page ' or . = ' Orders History Page ')]</value>
      <webElementGuid>f92513b3-20c4-45ae-9ff8-4ec19874312e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| 67b764c9c019fb1ad603baf1 |'])[1]/preceding::label[1]</value>
      <webElementGuid>cec2b1fb-3486-4f50-b5af-928d05d0942a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| 67b764c9c019fb1ad603baf4 |'])[1]/preceding::label[2]</value>
      <webElementGuid>bc69f488-6c54-4e8c-a8b1-fe1ce0b1041b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
