<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Home  SearchFiltersPrice RangeCateg_a389f4</name>
   <tag></tag>
   <elementGuidId>ff343bc2-0126-4553-ab53-4c5d62ebb984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='sidebar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sidebar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>750e8277-a907-4d48-b207-8e870918f801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar</value>
      <webElementGuid>fb6969d5-9db2-48a9-ba9f-8eab3785f8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen</value>
      <webElementGuid>e15e69e6-79cb-4c51-a8d9-90f50ea8b0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)</value>
      <webElementGuid>9e217080-da54-4acb-a18a-036d0daaf358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='sidebar']</value>
      <webElementGuid>ba41a469-1361-4119-9164-dbadc0620491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='women'])[1]/following::section[1]</value>
      <webElementGuid>13eadf5a-c064-4e03-86b1-0fb742aadf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='men'])[1]/following::section[1]</value>
      <webElementGuid>92d50c31-0f0b-4aab-bdb3-b9a6ca738581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>c7ef6fac-3446-440e-adcb-7775825d5c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'sidebar' and (text() = ' Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen' or . = ' Home | SearchFiltersPrice RangeCategoriesfashionelectronicshouseholdSub Categoriest-shirtsshirtsshoesmobileslaptopsSearch Formenwomen')]</value>
      <webElementGuid>b578265e-f5a6-4dc4-a4e0-8f4ca144d764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
