<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Press , , Enter, ,  to skip to c_ef5b00</name>
   <tag></tag>
   <elementGuidId>b86937eb-b113-48fe-85fb-ac829424ee09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-title']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Practice Test Automation&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f13292ec-6307-4d99-8398-6b172acab198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>305</value>
      <webElementGuid>e29427fa-cdf8-4a95-8c55-cb8b74094dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>249f8f9c-9c9f-4b2d-b5d2-5ae378ea320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/practicetestautomation.com/wp-content/uploads/2019/10/Logo-1.png?fit=305%2C96&amp;ssl=1</value>
      <webElementGuid>40e5537e-2302-4dec-a743-ceb43739f253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo</value>
      <webElementGuid>c14bb881-c0c1-4302-b5ea-8ccee0b44c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Practice Test Automation</value>
      <webElementGuid>1a51a529-a389-454a-81bd-a1f4bc26ad0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8e447b97-709a-46ca-b3dd-3edbef7e3f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i0.wp.com/practicetestautomation.com/wp-content/uploads/2019/10/Logo-1.png?w=305&amp;ssl=1 305w, https://i0.wp.com/practicetestautomation.com/wp-content/uploads/2019/10/Logo-1.png?resize=300%2C94&amp;ssl=1 300w</value>
      <webElementGuid>029b56e1-afe1-4bce-bbfb-dd68c6744eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 305px) 100vw, 305px</value>
      <webElementGuid>6f14ba0d-9fb1-4e16-bfc5-68c8a4b116a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-title&quot;)/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo&quot;]</value>
      <webElementGuid>0a6ad99d-b0d8-4bbc-bcc9-c4a9c94b5af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-title']/a/img</value>
      <webElementGuid>4b57e334-abfc-4a8a-a051-30e0f86a5d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Practice Test Automation']</value>
      <webElementGuid>342a8295-4886-4d02-b6ee-7c9081b5a8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>74d827dd-bb52-4d16-ba54-00e108f25ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/practicetestautomation.com/wp-content/uploads/2019/10/Logo-1.png?fit=305%2C96&amp;ssl=1' and @alt = 'Practice Test Automation']</value>
      <webElementGuid>2240238b-c0be-4c9e-a15d-4256119b70a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
