<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Hummingbird printed t-shirt</name>
   <tag></tag>
   <elementGuidId>9f718ad3-6122-40e7-8cc6-85e76730a583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Hummingbird printed t-shirt&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>503c836c-18e1-4333-b8ad-ac1e6d54bbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f9b5f1c9-c92b-45ec-9cd8-cc4d91fbf153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hummingbird printed t-shirt</value>
      <webElementGuid>642b22b6-24b3-4367-a6cf-3cb973ae5880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row product-container js-product-container&quot;]/div[@class=&quot;col-md-6&quot;]/h1[@class=&quot;h1&quot;]</value>
      <webElementGuid>686e532a-efa8-44ce-ba8d-787745930548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>72213f1e-f7d9-4e2d-b958-fca5ac3420f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/div[2]/h1</value>
      <webElementGuid>f7872d5c-d6b8-42ab-afad-076d46f0761c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::h1[1]</value>
      <webElementGuid>0cffa11b-9e43-4376-8941-5b81ce5f6ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::h1[1]</value>
      <webElementGuid>5e17fa6f-f639-4a60-886c-5e5e255898ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€28.68'])[1]/preceding::h1[1]</value>
      <webElementGuid>ce63ecf1-a656-45b6-947c-7492c0fe7056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€22.94'])[1]/preceding::h1[1]</value>
      <webElementGuid>2c58d7ba-7afb-45cc-a116-80084cdfcac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a865f3af-3f17-4673-88c3-9ad94faf89c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Hummingbird printed t-shirt' or . = 'Hummingbird printed t-shirt')]</value>
      <webElementGuid>623896ff-d985-48a1-972c-437bf9db01a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
