<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Mug The best is yet to come</name>
   <tag></tag>
   <elementGuidId>2528d532-cdd1-4041-a0a9-5c0e3f3b640b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Mug The best is yet to come&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>59877cc9-553e-4a64-b18d-d49e20813b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>65b8500a-0075-42f6-88f9-67aa94dd0806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mug The best is yet to come</value>
      <webElementGuid>b242c218-87f3-430b-8b4b-62cb596cbca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row product-container js-product-container&quot;]/div[@class=&quot;col-md-6&quot;]/h1[@class=&quot;h1&quot;]</value>
      <webElementGuid>0b6e4faa-69cb-43dd-bc2d-8cf2d212b120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>6fd9e6a9-edab-4871-b79f-ee7197689bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/div[2]/h1</value>
      <webElementGuid>d9997fd4-039f-493c-a0a2-0facc5fc4bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::h1[1]</value>
      <webElementGuid>221d11b8-9f52-4469-bf85-95439395e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::h1[1]</value>
      <webElementGuid>88d3d11a-0746-42dc-8b5f-4ae4027bbe2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€14.28'])[1]/preceding::h1[1]</value>
      <webElementGuid>2f895f2c-3a2d-4572-9d82-b6b419b1b128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax included'])[1]/preceding::h1[1]</value>
      <webElementGuid>11a1852a-c5e9-4080-92ea-91757690c438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>255a0688-bdbd-4341-9a13-75d26aed51bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Mug The best is yet to come' or . = 'Mug The best is yet to come')]</value>
      <webElementGuid>d64b9ac4-d5be-4f90-bb4b-67ccdb67084d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
