<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Product successfully added to your shopp_0bf508</name>
   <tag></tag>
   <elementGuidId>48986a78-1eb5-440a-a240-9c249b85c8e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myModalLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='myModalLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot; Product successfully added to your shopping cart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d4efcc19-9172-4d75-8c7d-5f2397d958fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title h6 text-sm-center</value>
      <webElementGuid>07ab4e07-5f49-4431-a89a-0bbd26c3c4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myModalLabel</value>
      <webElementGuid>0ae09475-214f-4848-b15a-2fc160004864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product successfully added to your shopping cart</value>
      <webElementGuid>b86aa052-0c73-476f-9434-28af72b95cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModalLabel&quot;)</value>
      <webElementGuid>5f5863e3-f31a-4b26-8226-401f20ed1059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>ad794502-b2f7-4d6b-abca-0ab916991eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='myModalLabel']</value>
      <webElementGuid>6f87b560-7fff-400b-b80b-b1075ca9ed51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blockcart-modal']/div/div/div/h4</value>
      <webElementGuid>5332e4b0-19a5-49d9-bb51-fec78f76d322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::h4[1]</value>
      <webElementGuid>efad51c7-dcfd-4013-be5d-0e6580b5049b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mug The best is yet to come'])[5]/preceding::h4[1]</value>
      <webElementGuid>eef38edd-096a-483e-afa6-82b217541419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product successfully added to your shopping cart']/parent::*</value>
      <webElementGuid>839bb297-1d76-4c26-bbf8-895fdfac83ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>6f60dc18-2399-4aa0-b57a-2b22064eba2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'myModalLabel' and (text() = 'Product successfully added to your shopping cart' or . = 'Product successfully added to your shopping cart')]</value>
      <webElementGuid>55c824ad-d601-4b54-8ab8-756b5fdaad4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
