<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Hide_framelive_1</name>
   <tag></tag>
   <elementGuidId>86f7144a-30b4-4c77-9539-6ccddd89c287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#framelive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='framelive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;framelive&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ca838ad1-1efe-4f69-8dbb-9bad536f4b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Frame of demo shop</value>
      <webElementGuid>428fb957-df88-4da9-812e-f6f9e0f8a58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>380ea38c-6e92-4d66-a72b-c25dac95706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>8e84bbe0-3e64-49ca-ba21-9f419c14a455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6f5feb5-c2e2-4782-9f6b-b3b3d6f88555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://tan-alarm.demo.prestashop.com/en/?id_module_showcased=undefined</value>
      <webElementGuid>3ecea5c0-e2f0-449e-b8d6-ab5c9fc49e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>5fee701c3a6347dd78cc160215f54655</value>
      <webElementGuid>4a2c1aac-85b9-43b3-a465-dda862e8176a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;framelive&quot;)</value>
      <webElementGuid>29ad39d4-7ed4-42a3-992d-841075bcf8e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='framelive']</value>
      <webElementGuid>3ef5c2ea-fa86-4188-b65a-486a96c517e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-wrapper']/iframe</value>
      <webElementGuid>1864a0f8-7fca-447c-af03-b94729bf77f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>48299cf6-4e2a-4b01-8b24-4aa2fae52d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://tan-alarm.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>10cb9ee8-369c-4d51-9fc4-72b1613532df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://arrogant-key.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>2a4b96b6-1830-4efe-b959-b7a58c85b142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://better-sock.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>af4b2628-33bc-4150-9010-c92a4cefadf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
