<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Hide_framelive</name>
   <tag></tag>
   <elementGuidId>2dc7ac83-2da3-408a-b9f0-6d5849057db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#framelive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='framelive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;framelive&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>815a3748-77af-4558-8f52-149d8ccd61e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Frame of demo shop</value>
      <webElementGuid>3b4dd745-533f-497e-afc6-01cebeb7e399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>2b580e5a-9a0a-46a6-a297-02dea8ae46f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>afa60a9a-fb94-494f-9424-c7b630622991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71294bdb-bb0f-4f2b-9362-1d56a67a16fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://confused-muscle.demo.prestashop.com/en/?id_module_showcased=undefined</value>
      <webElementGuid>ab3809c3-00f1-4fc0-a885-11712be0a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;framelive&quot;)</value>
      <webElementGuid>1881d24b-92f5-41a1-b1f3-7d883155b984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>d3d691b12430d2f8398d7c6619e7360f</value>
      <webElementGuid>0491d0cf-0ee6-44e9-8233-671004f5068a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='framelive']</value>
      <webElementGuid>1d5a96a7-d6b5-4e0d-bab4-aff707d86b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-wrapper']/iframe</value>
      <webElementGuid>03612517-798c-47e2-adf2-ceee54b8a40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>886cf9b1-7b64-4fc5-99f7-e0e5c45c5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://confused-muscle.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>609e51a7-5a1a-49fe-a8d1-a7fbe54ccaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://gas-join.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>fcd23899-c799-47c1-a9ff-9c8d8102f898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://lacking-cause.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>5648a264-fa4b-43ad-994f-6d3eee65726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://plucky-match.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>b3ed5ab4-66df-40d3-8e8d-fc219381ec60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
