<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4db1e565-0e75-41f3-96cc-34e8829583b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Mug The best is yet to come&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-product-list']/div/div[2]/article/div/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mug The best is yet to come&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>897ec9bf-4877-4563-b872-691710b102fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/6-home_default/mug-the-best-is-yet-to-come.jpg</value>
      <webElementGuid>f4e46de4-8577-44bb-bed2-3a3f3d30ca21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mug The best is yet to come</value>
      <webElementGuid>53f38901-3c6c-41e3-b470-cd60bef33c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>7be08f71-99c6-480e-b0f9-84c163d925c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-full-size-image-url</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/6-large_default/mug-the-best-is-yet-to-come.jpg</value>
      <webElementGuid>5d824a01-2d44-485a-8520-59912aa59beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>af8434a4-ef80-4e95-aa6c-cdbf1daf8756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>15aebc89-1a13-406b-bd36-c288b5a5284a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-product-list&quot;)/div[@class=&quot;products row&quot;]/div[@class=&quot;js-product product col-xs-12 col-sm-6 col-xl-3&quot;]/article[@class=&quot;product-miniature js-product-miniature&quot;]/div[@class=&quot;thumbnail-container reviews-loaded&quot;]/div[@class=&quot;thumbnail-top&quot;]/a[@class=&quot;thumbnail product-thumbnail&quot;]/picture[1]/img[1]</value>
      <webElementGuid>ac3c800a-15a1-42aa-91a4-234861500142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>6b8f2dd4-10d5-45e3-a7ec-26d831721943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-product-list']/div/div[2]/article/div/div/a/picture/img</value>
      <webElementGuid>68a939da-729f-47a9-aa99-e84fae9b5cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Mug The best is yet to come']</value>
      <webElementGuid>d7862899-664d-446c-988f-ce24c47b0e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/a/picture/img</value>
      <webElementGuid>f8327f8d-c6b0-4520-b0bf-3aff866bd23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lacking-cause.demo.prestashop.com/6-home_default/mug-the-best-is-yet-to-come.jpg' and @alt = 'Mug The best is yet to come']</value>
      <webElementGuid>269a1b11-aef9-4609-a2a1-85391337098d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
