<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>520b7838-e6b5-4aa4-92a5-67c724135287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Hummingbird printed t-shirt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/section/div/div/article/div/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hummingbird printed t-shirt&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a03ba808-e457-4bd2-981f-b0b6c9d30632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/1-home_default/hummingbird-printed-t-shirt.jpg</value>
      <webElementGuid>4b3c8c22-474e-4c93-a324-8df27aae7e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hummingbird printed t-shirt</value>
      <webElementGuid>99ad22fc-fbe6-41c5-a95a-69b4ca4873d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>74d9669b-8a90-4139-b225-edebf773bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-full-size-image-url</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/1-large_default/hummingbird-printed-t-shirt.jpg</value>
      <webElementGuid>90b06199-a161-4758-896d-9bb69239d5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>46b92d1f-0b6e-4a4d-bef0-a9e8d81d2f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>43d09783-3e2f-4d4a-97a8-7045e36ce61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;featured-products clearfix&quot;]/div[@class=&quot;products row&quot;]/div[@class=&quot;js-product product col-xs-12 col-sm-6 col-lg-4 col-xl-3&quot;]/article[@class=&quot;product-miniature js-product-miniature&quot;]/div[@class=&quot;thumbnail-container reviews-loaded&quot;]/div[@class=&quot;thumbnail-top&quot;]/a[@class=&quot;thumbnail product-thumbnail&quot;]/picture[1]/img[1]</value>
      <webElementGuid>2a795068-8c74-4a8b-89e9-9a710f3dbfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>717e4bb6-d8f6-457e-95a0-ee967d021494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/section/div/div/article/div/div/a/picture/img</value>
      <webElementGuid>d7dbdb4b-6cc6-4934-84c0-e0f7a690bee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hummingbird printed t-shirt']</value>
      <webElementGuid>4529544a-ca3d-4cf4-bfc2-7eb4771aa282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>7acdf13c-056b-4ead-b118-cde4d678f7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lacking-cause.demo.prestashop.com/1-home_default/hummingbird-printed-t-shirt.jpg' and @alt = 'Hummingbird printed t-shirt']</value>
      <webElementGuid>409ac5a2-bd77-43b9-bb5f-a76424cdc573</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
