<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>08a18a96-b021-4d87-8256-efd0c1eeaf8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Today is a good day Framed poster&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/section/div/div[5]/article/div/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Today is a good day Framed poster&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>29697b71-7586-4991-b3de-458753c55ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/5-home_default/today-is-a-good-day-framed-poster.jpg</value>
      <webElementGuid>3951eff5-4578-4bcc-852f-15250086d05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Today is a good day Framed poster</value>
      <webElementGuid>149d21f6-ebe3-4d6d-9995-e5d0286fed48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a5158d3c-d49c-4723-94cc-120c5ead06b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-full-size-image-url</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/5-large_default/today-is-a-good-day-framed-poster.jpg</value>
      <webElementGuid>b7dde92a-59cf-41f3-8721-edde3933ad96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>dfea0208-15ad-4941-851f-742eec7e98b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>138a13d3-84a5-48aa-acd5-cdfc6b5a8902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;featured-products clearfix&quot;]/div[@class=&quot;products row&quot;]/div[@class=&quot;js-product product col-xs-12 col-sm-6 col-lg-4 col-xl-3&quot;]/article[@class=&quot;product-miniature js-product-miniature&quot;]/div[@class=&quot;thumbnail-container reviews-loaded&quot;]/div[@class=&quot;thumbnail-top&quot;]/a[@class=&quot;thumbnail product-thumbnail&quot;]/picture[1]/img[1]</value>
      <webElementGuid>d1a3f0c5-5beb-4840-a444-0b8ec4d19e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>a3d352c7-e98c-477d-8c9e-c321b27e4e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/section/div/div[5]/article/div/div/a/picture/img</value>
      <webElementGuid>9d111f59-5c10-4c56-b250-5ac8b0a4dc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Today is a good day Framed poster']</value>
      <webElementGuid>b9fc8cf9-41d4-457c-8be6-d580081863a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/article/div/div/a/picture/img</value>
      <webElementGuid>9f9e5e05-e09a-4cef-88d4-db46cb726304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lacking-cause.demo.prestashop.com/5-home_default/today-is-a-good-day-framed-poster.jpg' and @alt = 'Today is a good day Framed poster']</value>
      <webElementGuid>a7efd749-74bf-4b20-960a-ad35eabe940a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
