<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__logo img-fluid</name>
   <tag></tag>
   <elementGuidId>2848494c-7cc9-40ab-b4a2-21b8e5eb7bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_logo']/h1/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PrestaShop&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7f946080-ebb9-4a21-8df3-68feed46a2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo img-fluid</value>
      <webElementGuid>1a4144f6-f59a-448b-b4bb-3264bfdd1b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://gas-join.demo.prestashop.com/img/logo.png</value>
      <webElementGuid>b96238e6-9807-4c13-a838-0284f5e77405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PrestaShop</value>
      <webElementGuid>13eb3441-597d-403c-969f-e2000aea5286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>aafe090a-13c2-40c7-8b78-8b0fe70ac937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>aa562d4b-34b2-43cf-b16b-63cdfcaa8ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_desktop_logo&quot;)/h1[1]/a[1]/img[@class=&quot;logo img-fluid&quot;]</value>
      <webElementGuid>1e2ce33e-bf42-4345-89f2-8277890e2eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>c30eff63-c0cf-45ef-be5e-b0e6a5b2b095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_logo']/h1/a/img</value>
      <webElementGuid>0d8ad8da-bd1e-4c7b-9a5c-f8bb7672d9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='PrestaShop']</value>
      <webElementGuid>184d8901-451b-4cf9-a730-93e9604a7d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fcf78f7d-041a-493e-ab03-8359f3fe1501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://gas-join.demo.prestashop.com/img/logo.png' and @alt = 'PrestaShop']</value>
      <webElementGuid>22f7e8b4-ac41-4b62-b95d-4cdf827d57d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_logo']/a/img</value>
      <webElementGuid>75ee0e83-86bf-4657-a928-4e3aeffc1d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lacking-cause.demo.prestashop.com/img/logo.png' and @alt = 'PrestaShop']</value>
      <webElementGuid>6fe2bd2b-a296-4ab6-b5a8-6a35799f27cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://plucky-match.demo.prestashop.com/img/logo.png' and @alt = 'PrestaShop']</value>
      <webElementGuid>294c7493-bff3-4328-90da-7cca3624a84e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
