<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__logo img-fluid_1</name>
   <tag></tag>
   <elementGuidId>a7e8760e-99a9-445f-9e71-52cdeefd4ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='PrestaShop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PrestaShop&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cff41b71-d483-41e8-b281-21599782ef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo img-fluid</value>
      <webElementGuid>f8837257-5507-4dec-aed7-fd45e1019be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lacking-cause.demo.prestashop.com/img/logo.png</value>
      <webElementGuid>57b6c412-e7f5-437a-a978-e0f5ea78c099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>PrestaShop</value>
      <webElementGuid>a7919b3b-106e-4adf-b514-ba6419fc5ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ccdc5b3a-1e29-4f85-9c53-a1da0bb0a61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>db4bee0e-d9fe-43e9-859d-353abd9bdc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_desktop_logo&quot;)/h1[1]/a[1]/img[@class=&quot;logo img-fluid&quot;]</value>
      <webElementGuid>e2dfc5b6-d7cd-4a6c-84e6-a2e6f99a2803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>d7c9443d-a082-4e22-a77e-3f0183c92533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_logo']/h1/a/img</value>
      <webElementGuid>1dedb0a8-1862-40e3-bdf0-060f6e2c025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='PrestaShop']</value>
      <webElementGuid>5814ea31-d4ce-4a46-839e-f13f2b99c1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9426e196-6fbb-484a-a5ef-8f388c921d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lacking-cause.demo.prestashop.com/img/logo.png' and @alt = 'PrestaShop']</value>
      <webElementGuid>9143d73c-13c9-432e-b487-cbd780594e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_logo']/a/img</value>
      <webElementGuid>6604221e-c717-4d07-ae2f-3fcb1ba682c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://plucky-match.demo.prestashop.com/img/logo.png' and @alt = 'PrestaShop']</value>
      <webElementGuid>1eeda77e-1663-40d1-9a63-59be812545f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
