<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>c741412c-50b6-4384-a9eb-dd7eeeebf6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f84abe42-fcd8-42cc-8b0e-e4bbc11f9f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-password</value>
      <webElementGuid>1b2fd445-2d78-4a60-867d-3e18b18b32b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control js-child-focus js-visible-password</value>
      <webElementGuid>56f71771-c727-42b5-b46d-bfae03168a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cf41be6b-d159-455a-b8f1-9de2a8baa3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password input</value>
      <webElementGuid>194b2e25-1f2c-4055-b124-8fd2fcc25872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b6ddbf79-a77e-4d01-a640-25aa44941444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>26f0fdd4-4062-44d7-902b-ad4e94ba677f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxlength</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>67781f60-ef06-44c8-be63-3dd57748c25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minscore</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>eeba119a-89d9-44d6-be7b-9a52bfe0db0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>6a8a548b-6da9-4cdd-a823-aa5b9f186eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{5,}</value>
      <webElementGuid>5a77e557-2694-453f-96ac-4090b016e93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-password&quot;)</value>
      <webElementGuid>233d087d-f2a7-40a9-a727-14019ba45825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Prestashop/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>9d0e0eb1-a862-4b20-b1e5-aa979400fb2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-password']</value>
      <webElementGuid>7231c99d-1b0f-41ba-9d59-c571d881921c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div[2]/div/div/input</value>
      <webElementGuid>673fec28-cfa8-4e67-8c68-70d97ce71867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0453bd16-911d-4af0-95ee-01fde3ef39d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-password' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>ab9ed94e-e3f7-4785-af5f-3a35799c1481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
